#!/usr/bin/env python3
"""Append rows to the spine-shape-evolution.md doc for tracked entities.

Usage:
  update_evolution.py --diff <diff.json> --snapshot <snapshot.json> \\
                      --tracked <tracked.txt> --evo <evo.md> --tag vX.Y.Z

Idempotency: rows already present for this tag are removed before appending.
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path

HEADER = """# Spine entity shape evolution

Curated per-version log of selected entities (configured in
`.claude/skills/generate-decoder/tracked-entities.txt`). Generated by
`/generate-decoder`. Full snapshots: `docs/research/.shapes/v*.json`.

| Version | Entity | Change |
|---|---|---|
"""


def read_tracked(path: Path) -> list[str]:
    if not path.exists():
        return []
    out = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        out.append(line)
    return out


def fmt_change(diff: dict, snapshot: dict, entity: str) -> str:
    if entity in diff.get("added_messages", []):
        return "added (first appearance)"
    if entity in diff.get("removed_messages", []):
        return "removed"
    changed = diff.get("changed_messages", {})
    if entity in changed:
        c = changed[entity]
        parts = []
        if c.get("added_fields"):
            parts.append(
                "+" + ",".join(f["name"] for f in c["added_fields"])
            )
        if c.get("removed_fields"):
            parts.append(
                "-" + ",".join(f["name"] for f in c["removed_fields"])
            )
        if c.get("type_changed_fields"):
            parts.append(
                "~" + ",".join(f["name"] for f in c["type_changed_fields"])
            )
        return " ".join(parts) or "unchanged"
    if entity in snapshot["messages"]:
        return "unchanged"
    return "n/a (not present)"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--diff", required=True)
    ap.add_argument("--snapshot", required=True)
    ap.add_argument("--tracked", required=True)
    ap.add_argument("--evo", required=True)
    ap.add_argument("--tag", required=True)
    args = ap.parse_args()

    diff = json.loads(Path(args.diff).read_text())
    snapshot = json.loads(Path(args.snapshot).read_text())
    tracked = read_tracked(Path(args.tracked))
    evo_path = Path(args.evo)

    # Build rows for this tag.
    rows = []
    for entity in tracked:
        change = fmt_change(diff, snapshot, entity)
        rows.append(f"| {args.tag} | `{entity}` | {change} |")

    # Ensure file exists with header.
    if not evo_path.exists():
        evo_path.parent.mkdir(parents=True, exist_ok=True)
        evo_path.write_text(HEADER)

    # Remove any prior rows for this exact tag (idempotency).
    existing = evo_path.read_text().splitlines()
    tag_row_re = re.compile(rf"^\|\s*{re.escape(args.tag)}\s*\|")
    kept = [ln for ln in existing if not tag_row_re.match(ln)]
    # Append the new rows.
    kept.extend(rows)
    evo_path.write_text("\n".join(kept) + "\n")
    print(f"   appended {len(rows)} row(s) to {evo_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
