-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.2.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_2.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (102, 'v0.1.2')
ON CONFLICT (tag) DO NOTHING;

-- pocket.proof.SessionSMT → session_smt_history (first appearance)
CREATE TABLE IF NOT EXISTS session_smt_history (
  supplier_operator_address TEXT NOT NULL,
  session_header JSONB NULL,
  smt_root BYTEA NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT session_smt_history_pk PRIMARY KEY (supplier_operator_address, block_height),
  CONSTRAINT session_smt_history_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
CREATE INDEX IF NOT EXISTS session_smt_history_current_idx ON session_smt_history (supplier_operator_address, block_height DESC);

-- pocket.application.Application → application_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN application_history.delegatee_gateway_addresses IS 'TODO_MAINNET_MIGRATION(@bryanchriswhite): Rename `delegatee_gateway_addresses` to `gateway_addresses_delegated_to`. Ensure to rename all relevant configs, comments, variables, function names, etc as well. Non-nullable list of Bech32 encoded delegatee Gateway addresses';

-- pocket.shared.Service → service_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN service_history.name IS 'TODO_MAINNET_MIGRATION(@bryanchriswhite): Either remove this or rename it to alias.';

-- pocket.migration.MorseApplication → morse_application_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN morse_application_history.jailed IS 'TODO_MAINNET_MIGRATION(@Olshansk):  Should status and/or jailed be considered during the migration, and if so, how?';

-- pocket.migration.MorseValidator → morse_validator_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN morse_validator_history.jailed IS 'TODO_MAINNET_MIGRATION(@Olshansk):  Should status and/or jailed be considered during the migration, and if so, how?';

-- pocket.migration.MorseClaimableAccount → morse_claimable_account_history (additive)
-- REMOVED in v0.1.2: column public_key kept (append-only, ADR-005).

-- pocket.migration.MsgClaimMorseAccount → msg_claim_morse_account (additive)
ALTER TABLE msg_claim_morse_account ADD COLUMN IF NOT EXISTS shannon_signing_address TEXT NULL;
ALTER TABLE msg_claim_morse_account ADD COLUMN IF NOT EXISTS morse_public_key BYTEA NULL;
COMMENT ON COLUMN msg_claim_morse_account.shannon_signing_address IS 'The bech32-encoded address of the Shannon account which is signing for this message. This account is liable for any fees incurred by violating the constraints of Morse account/actor claim message fee waiving; the tx contains ONE OR MORE Morse account/actor claim messages AND has EXACTLY ONE signer.';
COMMENT ON COLUMN msg_claim_morse_account.morse_public_key IS 'The ed25519 public key of the morse account with morse_src_address.';
-- REMOVED in v0.1.2: column morse_src_address kept (append-only, ADR-005).

-- pocket.migration.MsgClaimMorseApplication → msg_claim_morse_application (additive)
ALTER TABLE msg_claim_morse_application ADD COLUMN IF NOT EXISTS shannon_signing_address TEXT NULL;
ALTER TABLE msg_claim_morse_application ADD COLUMN IF NOT EXISTS morse_public_key BYTEA NULL;
COMMENT ON COLUMN msg_claim_morse_application.shannon_signing_address IS 'The bech32-encoded address of the Shannon account which is signing for this message. This account is liable for any fees incurred by violating the constraints of Morse account/actor claim message fee waiving; the tx contains ONE OR MORE Morse account/actor claim messages AND has EXACTLY ONE signer.';
COMMENT ON COLUMN msg_claim_morse_application.morse_public_key IS 'The ed25519 public key of the morse account with morse_src_address.';
-- REMOVED in v0.1.2: column morse_src_address kept (append-only, ADR-005).

-- pocket.migration.MsgClaimMorseSupplier → msg_claim_morse_supplier (additive)
ALTER TABLE msg_claim_morse_supplier ADD COLUMN IF NOT EXISTS shannon_signing_address TEXT NULL;
ALTER TABLE msg_claim_morse_supplier ADD COLUMN IF NOT EXISTS morse_public_key BYTEA NULL;
COMMENT ON COLUMN msg_claim_morse_supplier.shannon_signing_address IS 'The bech32-encoded address of the Shannon account which is signing for this message. This account is liable for any fees incurred by violating the constraints of Morse account/actor claim message fee waiving; the tx contains ONE OR MORE Morse account/actor claim messages AND has EXACTLY ONE signer.';
COMMENT ON COLUMN msg_claim_morse_supplier.morse_public_key IS 'The ed25519 public key of the morse account with morse_src_address.';
-- REMOVED in v0.1.2: column morse_src_address kept (append-only, ADR-005).

-- pocket.migration.Params → migration_params_history (additive)
ALTER TABLE migration_params_history ADD COLUMN IF NOT EXISTS waive_morse_claim_gas_fees BOOLEAN NULL;
COMMENT ON COLUMN migration_params_history.waive_morse_claim_gas_fees IS 'waive_morse_claim_gas_fees is a feature flag used to enable/disable the waiving of gas fees for txs that: - Contain exactly one secp256k1 signer - Contain at least one Morse account/actor claim messages - Do not contain any other messages other than Morse account/actor claim messages';

-- pocket.proof.Params → proof_params_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN proof_params_history.proof_requirement_threshold_amount IS 'proof_requirement_threshold is the session cost (i.e. compute unit consumption) threshold which asserts that a session MUST have a corresponding proof when its cost is equal to or above the threshold. This is in contrast to the this requirement being determined probabilistically via ProofRequestProbability.  TODO_MAINNET_MIGRATION: Consider renaming this to `proof_requirement_threshold_upokt`.';
COMMENT ON COLUMN proof_params_history.proof_requirement_threshold_denom IS 'proof_requirement_threshold is the session cost (i.e. compute unit consumption) threshold which asserts that a session MUST have a corresponding proof when its cost is equal to or above the threshold. This is in contrast to the this requirement being determined probabilistically via ProofRequestProbability.  TODO_MAINNET_MIGRATION: Consider renaming this to `proof_requirement_threshold_upokt`.';
COMMENT ON COLUMN proof_params_history.proof_missing_penalty_amount IS 'proof_missing_penalty is the number of tokens (uPOKT) which should be slashed from a supplier when a proof is required (either via proof_requirement_threshold or proof_missing_penalty) but is not provided. TODO_MAINNET_MIGRATION: Consider renaming this to `proof_missing_penalty_upokt`.';
COMMENT ON COLUMN proof_params_history.proof_missing_penalty_denom IS 'proof_missing_penalty is the number of tokens (uPOKT) which should be slashed from a supplier when a proof is required (either via proof_requirement_threshold or proof_missing_penalty) but is not provided. TODO_MAINNET_MIGRATION: Consider renaming this to `proof_missing_penalty_upokt`.';
COMMENT ON COLUMN proof_params_history.proof_submission_fee_amount IS 'proof_submission_fee is the number of tokens (uPOKT) which should be paid by the supplier operator when submitting a proof. This is needed to account for the cost of storing proofs onchain and prevent spamming (i.e. sybil bloat attacks) the network with non-required proofs. TODO_MAINNET_MIGRATION: Consider renaming this to `proof_submission_fee_upokt`.';
COMMENT ON COLUMN proof_params_history.proof_submission_fee_denom IS 'proof_submission_fee is the number of tokens (uPOKT) which should be paid by the supplier operator when submitting a proof. This is needed to account for the cost of storing proofs onchain and prevent spamming (i.e. sybil bloat attacks) the network with non-required proofs. TODO_MAINNET_MIGRATION: Consider renaming this to `proof_submission_fee_upokt`.';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE msg_claim_morse_account DROP COLUMN IF EXISTS shannon_signing_address;
ALTER TABLE msg_claim_morse_account DROP COLUMN IF EXISTS morse_public_key;
ALTER TABLE msg_claim_morse_application DROP COLUMN IF EXISTS shannon_signing_address;
ALTER TABLE msg_claim_morse_application DROP COLUMN IF EXISTS morse_public_key;
ALTER TABLE msg_claim_morse_supplier DROP COLUMN IF EXISTS shannon_signing_address;
ALTER TABLE msg_claim_morse_supplier DROP COLUMN IF EXISTS morse_public_key;
ALTER TABLE migration_params_history DROP COLUMN IF EXISTS waive_morse_claim_gas_fees;
DROP TABLE IF EXISTS session_smt_history CASCADE;
DELETE FROM decoder_version WHERE tag = 'v0.1.2';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
