-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.5.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_5.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (105, 'v0.1.5')
ON CONFLICT (tag) DO NOTHING;

-- pocket.migration.MsgImportMorseClaimableAccounts → msg_import_morse_claimable_accounts (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN msg_import_morse_claimable_accounts.morse_account_state IS 'the account state derived from the Morse state export and the `pocketd tx migration collect-morse-accounts` command.';
COMMENT ON COLUMN msg_import_morse_claimable_accounts.morse_account_state_hash IS 'Additional documentation: - pocket util export-genesis-for-migration --help - pocketd tx migration collect-morse-accounts --help';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DELETE FROM decoder_version WHERE tag = 'v0.1.5';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
