-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.8.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_8.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (108, 'v0.1.8')
ON CONFLICT (tag) DO NOTHING;

-- pocket.application.Application → application_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN application_history.service_configs IS 'CRITICAL: Must contain EXACTLY ONE service config - Enforces a single service configuration per application to prevent over-servicing. - Field is repeated for legacy reasons and potential future compatibility. - References for rationale: - https://github.com/pokt-network/poktroll/pull/750#discussion_r1735025033 - https://www.notion.so/buildwithgrove/Off-chain-Application-Stake-Tracking-6a8bebb107db4f7f9dc62cbe7ba555f7';
COMMENT ON COLUMN application_history.delegatee_gateway_addresses IS 'TODO_MAINNET_MIGRATION(@bryanchriswhite): Rename `delegatee_gateway_addresses` to `gateway_addresses_delegated_to` for better clarity and consistency. - Update all related configs, comments, variables, and function names throughout the codebase to reflect this change. - This field is a non-nullable list of Bech32-encoded delegatee Gateway addresses.';

-- pocket.shared.Service → service_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN service_history.name IS 'TODO_POST_MAINNET: Rename service.name to service.description';
COMMENT ON COLUMN service_history.compute_units_per_relay IS 'The cost of a single relay for this service in terms of compute units. Must be used alongside the global ''compute_units_to_tokens_multiplier'' to calculate the cost of a relay for this service. cost_per_relay_for_specific_service = compute_units_per_relay_for_specific_service * compute_units_to_tokens_multiplier_global_value';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DELETE FROM decoder_version WHERE tag = 'v0.1.8';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
