-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.11.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_11.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (111, 'v0.1.11')
ON CONFLICT (tag) DO NOTHING;

-- pocket.migration.MsgRecoverMorseAccount → msg_recover_morse_account (first appearance)
CREATE TABLE IF NOT EXISTS msg_recover_morse_account (
  authority TEXT NULL,
  shannon_dest_address TEXT NULL,
  morse_src_address TEXT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT msg_recover_morse_account_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT msg_recover_morse_account_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('msg_recover_morse_account', 'block_time', if_not_exists => TRUE);
COMMENT ON COLUMN msg_recover_morse_account.authority IS 'The bech32-encoded address of the migration module authority account ("gov" module address by default). ONLY the authority, or its delegates, MAY recover Morse recoverable accounts.';
COMMENT ON COLUMN msg_recover_morse_account.shannon_dest_address IS 'The bech32-encoded address of the Shannon account to which the Morse account''s stake(s) and/or balance(s) will be minted (recovered) as liquid Shannon tokens.';
COMMENT ON COLUMN msg_recover_morse_account.morse_src_address IS 'EITHER: - The hex-encoded address of the recoverable Morse account whose stake(s) and/or balance(s) will be recovered. This address MAY be invalid but NEVER empty. E.g.: 00f9900606fa3d5c9179fc0c8513078a53a2073e - The name of a Morse module account whose balance will be recovered. E.g. "dao" or "fee-collector"';

-- pocket.migration.MsgClaimMorseSupplier → msg_claim_morse_supplier (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN msg_claim_morse_supplier.morse_signature IS 'TODO_MAINNET(@bryanchriswhite, #1126): Rename to `morse_src_owner_signature`.';

-- pocket.migration.Params → migration_params_history (additive)
ALTER TABLE migration_params_history ADD COLUMN IF NOT EXISTS allow_morse_account_import_overwrite BOOLEAN NULL;
COMMENT ON COLUMN migration_params_history.allow_morse_account_import_overwrite IS 'allow_morse_account_import_overwrite is a feature flag which is used to enable/disable the re-importing of Morse claimable accounts by the authority. Such a re-import will: - Ignore (i.e. leave) ALL claimed destination Shannon accounts/actors - Delete ALL existing onchain MorseClaimableAccounts - Import the new set of MorseClaimableAccounts from the provided MsgImportMorseClaimableAccounts This is useful for testing purposes, but should be disabled in production.';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE migration_params_history DROP COLUMN IF EXISTS allow_morse_account_import_overwrite;
DROP TABLE IF EXISTS msg_recover_morse_account CASCADE;
DELETE FROM decoder_version WHERE tag = 'v0.1.11';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
