-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.12.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_12.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (112, 'v0.1.12')
ON CONFLICT (tag) DO NOTHING;

-- cosmos.benchmark.v1.MsgLoadTest → cosmos_benchmark_v1_msg_load_test (first appearance)
CREATE TABLE IF NOT EXISTS cosmos_benchmark_v1_msg_load_test (
  caller BYTEA NULL,
  ops JSONB NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cosmos_benchmark_v1_msg_load_test_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT cosmos_benchmark_v1_msg_load_test_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('cosmos_benchmark_v1_msg_load_test', 'block_time', if_not_exists => TRUE);

-- cosmos.counter.v1.MsgIncreaseCounter → cosmos_counter_v1_msg_increase_counter (first appearance)
CREATE TABLE IF NOT EXISTS cosmos_counter_v1_msg_increase_counter (
  signer TEXT NULL,
  count BIGINT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cosmos_counter_v1_msg_increase_counter_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT cosmos_counter_v1_msg_increase_counter_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('cosmos_counter_v1_msg_increase_counter', 'block_time', if_not_exists => TRUE);
COMMENT ON COLUMN cosmos_counter_v1_msg_increase_counter.signer IS 'signer is the address that controls the module (defaults to x/gov unless overwritten).';
COMMENT ON COLUMN cosmos_counter_v1_msg_increase_counter.count IS 'count is the number of times to increment the counter.';

-- cosmos.epochs.v1beta1.EventEpochEnd → cosmos_epochs_vb1_event_epoch_end (first appearance)
CREATE TABLE IF NOT EXISTS cosmos_epochs_vb1_event_epoch_end (
  epoch_number BIGINT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cosmos_epochs_vb1_event_epoch_end_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT cosmos_epochs_vb1_event_epoch_end_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('cosmos_epochs_vb1_event_epoch_end', 'block_time', if_not_exists => TRUE);

-- cosmos.epochs.v1beta1.EventEpochStart → cosmos_epochs_vb1_event_epoch_start (first appearance)
CREATE TABLE IF NOT EXISTS cosmos_epochs_vb1_event_epoch_start (
  epoch_number BIGINT NULL,
  epoch_start_time BIGINT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cosmos_epochs_vb1_event_epoch_start_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT cosmos_epochs_vb1_event_epoch_start_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('cosmos_epochs_vb1_event_epoch_start', 'block_time', if_not_exists => TRUE);

-- cosmos.epochs.v1beta1.GenesisState → cosmos_epochs_genesis_state (first appearance)
CREATE TABLE IF NOT EXISTS cosmos_epochs_genesis_state (
  epochs JSONB NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cosmos_epochs_genesis_state_pk PRIMARY KEY (block_height),
  CONSTRAINT cosmos_epochs_genesis_state_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);

-- cosmos.protocolpool.v1.GenesisState → cosmos_protocolpool_genesis_state (first appearance)
CREATE TABLE IF NOT EXISTS cosmos_protocolpool_genesis_state (
  continuous_funds JSONB NULL,
  params JSONB NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cosmos_protocolpool_genesis_state_pk PRIMARY KEY (block_height),
  CONSTRAINT cosmos_protocolpool_genesis_state_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
COMMENT ON COLUMN cosmos_protocolpool_genesis_state.continuous_funds IS 'ContinuousFunds defines the continuous funds at genesis.';
COMMENT ON COLUMN cosmos_protocolpool_genesis_state.params IS 'Params defines the parameters of this module, currently only contains the denoms that will be used for continuous fund distributions.';

-- cosmos.protocolpool.v1.MsgCancelContinuousFund → cosmos_protocolpool_v1_msg_cancel_continuous_fund (first appearance)
CREATE TABLE IF NOT EXISTS cosmos_protocolpool_v1_msg_cancel_continuous_fund (
  authority TEXT NULL,
  recipient TEXT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cosmos_protocolpool_v1_msg_cancel_continuous_fund_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT cosmos_protocolpool_v1_msg_cancel_continuous_fund_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('cosmos_protocolpool_v1_msg_cancel_continuous_fund', 'block_time', if_not_exists => TRUE);
COMMENT ON COLUMN cosmos_protocolpool_v1_msg_cancel_continuous_fund.authority IS 'Authority is the account address of authority.';
COMMENT ON COLUMN cosmos_protocolpool_v1_msg_cancel_continuous_fund.recipient IS 'Recipient is the account address string of the recipient whose funds are to be cancelled.';

-- cosmos.protocolpool.v1.MsgCommunityPoolSpend → cosmos_protocolpool_v1_msg_community_pool_spend (first appearance)
CREATE TABLE IF NOT EXISTS cosmos_protocolpool_v1_msg_community_pool_spend (
  authority TEXT NULL,
  recipient TEXT NULL,
  amount BIGINT NULL,
  amount_denom TEXT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cosmos_protocolpool_v1_msg_community_pool_spend_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT cosmos_protocolpool_v1_msg_community_pool_spend_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('cosmos_protocolpool_v1_msg_community_pool_spend', 'block_time', if_not_exists => TRUE);
COMMENT ON COLUMN cosmos_protocolpool_v1_msg_community_pool_spend.authority IS 'Authority is the address that controls the module (defaults to x/gov unless overwritten).';

-- cosmos.protocolpool.v1.MsgCreateContinuousFund → cosmos_protocolpool_v1_msg_create_continuous_fund (first appearance)
CREATE TABLE IF NOT EXISTS cosmos_protocolpool_v1_msg_create_continuous_fund (
  authority TEXT NULL,
  recipient TEXT NULL,
  percentage TEXT NULL,
  expiry JSONB NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cosmos_protocolpool_v1_msg_create_continuous_fund_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT cosmos_protocolpool_v1_msg_create_continuous_fund_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('cosmos_protocolpool_v1_msg_create_continuous_fund', 'block_time', if_not_exists => TRUE);
COMMENT ON COLUMN cosmos_protocolpool_v1_msg_create_continuous_fund.authority IS 'Authority is the address that controls the module (defaults to x/gov unless overwritten).';
COMMENT ON COLUMN cosmos_protocolpool_v1_msg_create_continuous_fund.recipient IS 'Recipient address of the account receiving funds.';
COMMENT ON COLUMN cosmos_protocolpool_v1_msg_create_continuous_fund.percentage IS 'Percentage is the percentage of funds to be allocated from Community pool.';
COMMENT ON COLUMN cosmos_protocolpool_v1_msg_create_continuous_fund.expiry IS 'Optional, if expiry is set, removes the state object when expired.';

-- cosmos.protocolpool.v1.MsgFundCommunityPool → cosmos_protocolpool_v1_msg_fund_community_pool (first appearance)
CREATE TABLE IF NOT EXISTS cosmos_protocolpool_v1_msg_fund_community_pool (
  depositor TEXT NULL,
  amount BIGINT NULL,
  amount_denom TEXT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cosmos_protocolpool_v1_msg_fund_community_pool_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT cosmos_protocolpool_v1_msg_fund_community_pool_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('cosmos_protocolpool_v1_msg_fund_community_pool', 'block_time', if_not_exists => TRUE);

-- cosmos.protocolpool.v1.MsgUpdateParams → cosmos_protocolpool_v1_msg_update_params (first appearance)
CREATE TABLE IF NOT EXISTS cosmos_protocolpool_v1_msg_update_params (
  authority TEXT NULL,
  params JSONB NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cosmos_protocolpool_v1_msg_update_params_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT cosmos_protocolpool_v1_msg_update_params_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('cosmos_protocolpool_v1_msg_update_params', 'block_time', if_not_exists => TRUE);
COMMENT ON COLUMN cosmos_protocolpool_v1_msg_update_params.authority IS 'authority is the address that controls the module (defaults to x/gov unless overwritten).';
COMMENT ON COLUMN cosmos_protocolpool_v1_msg_update_params.params IS 'params defines the x/protocolpool parameters to update.  NOTE: All parameters must be supplied.';

-- cosmos.protocolpool.v1.Params → cosmos_protocolpool_params_history (first appearance)
CREATE TABLE IF NOT EXISTS cosmos_protocolpool_params_history (
  enabled_distribution_denoms TEXT[] NULL,
  distribution_frequency BIGINT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cosmos_protocolpool_params_history_pk PRIMARY KEY (block_height),
  CONSTRAINT cosmos_protocolpool_params_history_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
COMMENT ON COLUMN cosmos_protocolpool_params_history.enabled_distribution_denoms IS 'EnabledDistributionDenoms lists the denoms that are allowed to be distributed. This is to avoid spending time distributing undesired tokens to continuous funds and budgets.';
COMMENT ON COLUMN cosmos_protocolpool_params_history.distribution_frequency IS 'DistributionFrequency is the frequency (in terms of blocks) that funds are distributed out from the x/protocolpool module.';

-- pocket.migration.EventMorseAccountRecovered → event_morse_account_recovered (first appearance)
CREATE TABLE IF NOT EXISTS event_morse_account_recovered (
  session_end_height BIGINT NULL,
  recovered_balance_amount BIGINT NULL,
  recovered_balance_denom TEXT NULL,
  shannon_dest_address TEXT NULL,
  morse_src_address TEXT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT event_morse_account_recovered_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT event_morse_account_recovered_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('event_morse_account_recovered', 'block_time', if_not_exists => TRUE);
COMMENT ON COLUMN event_morse_account_recovered.session_end_height IS 'The session end height (on Shannon) in which the recovery was committed (i.e. claimed).';
COMMENT ON COLUMN event_morse_account_recovered.recovered_balance_amount IS 'The total balance which was recovered: - Includes both unstaked and staked balances (consolidated) - Auto-liquidates both unstaked and staked balances at once';
COMMENT ON COLUMN event_morse_account_recovered.recovered_balance_denom IS 'The total balance which was recovered: - Includes both unstaked and staked balances (consolidated) - Auto-liquidates both unstaked and staked balances at once';
COMMENT ON COLUMN event_morse_account_recovered.shannon_dest_address IS 'The bech32-encoded address of the Shannon account to which the recovered balance was minted.';
COMMENT ON COLUMN event_morse_account_recovered.morse_src_address IS 'The hex-encoded address of the Morse account whose balance and stakes have been recovered. This address MUST be in the recovery allow list and could be of types such as: - Unreachable/Locked EOA, Supplier or Application address - Module account - Invalid address (too short, too long, or non-hexadecimal format)';

-- pocket.migration.MorseValidator → morse_validator_history (additive)
ALTER TABLE morse_validator_history ADD COLUMN IF NOT EXISTS output_address BYTEA NULL;
COMMENT ON COLUMN morse_validator_history.output_address IS 'Morse custodial (i.e. owner) address, which owns the staked tokens of the operator. Binary representation of the Morse address corresponding to a Morse account''s ed25519 public key. See ''pocket nodes --help'' for more information. Note that this refers to the Morse CLI.';
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN morse_validator_history.address IS 'Morse non-custodial (i.e. operator) address. If output_address is not set, this is the custodial address. Binary representation of the Morse address corresponding to a Morse node''s ed25519 public key. See ''pocket nodes --help'' for more information. Note that this refers to the Morse CLI.';
COMMENT ON COLUMN morse_validator_history.public_key IS 'Binary representation of a Morse node''s ed25519 public key.';

-- pocket.migration.MorseClaimableAccount → morse_claimable_account_history (additive)
ALTER TABLE morse_claimable_account_history ADD COLUMN IF NOT EXISTS morse_output_address TEXT NULL;
COMMENT ON COLUMN morse_claimable_account_history.morse_output_address IS 'ONLY applicable to Morse node/supplier accounts. Hex-encoded address of the Morse output account/wallet associated with the Morse node/supplier. - E.g.: 00f9900606fa3d5c9179fc0c8513078a53a2073e - Morse custodial (i.e. owner) address, which owns the staked tokens of the operator. See ''pocket nodes --help'' for more information. Note that this refers to the Morse CLI.';
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN morse_claimable_account_history.shannon_dest_address IS 'bech32-encoded address of the Shannon account to mint claimed balance Intended to remain empty until the account is claimed';
COMMENT ON COLUMN morse_claimable_account_history.morse_src_address IS 'Hex-encoded address of the Morse account whose balance will be claimed. If this MorseClaimableAccount represents a Morse node/supplier: - Morse non-custodial (i.e. operator) address. - If morse_output_address is not set, this is the custodial address. - See ''pocket nodes --help'' for more information. Note that this refers to the Morse CLI.';
COMMENT ON COLUMN morse_claimable_account_history.unstaked_balance_amount IS 'Unstaked upokt tokens (account balance) available for claiming';
COMMENT ON COLUMN morse_claimable_account_history.unstaked_balance_denom IS 'Unstaked upokt tokens (account balance) available for claiming';
COMMENT ON COLUMN morse_claimable_account_history.supplier_stake_amount IS 'Staked tokens for supplier actor corresponding to this account address DEV_NOTE: Context for Morse: - Supplier = Servicer or Node (not a full node) in Morse - All Validators are Servicers; not all Servicers are Validators - Top 100 staked Servicers are validators (automatic) - Only accounts for servicer stake balance transition TODO_MAINNET(@Olshansk): Develop strategy for bootstrapping validators in Shannon with cosmos ecosystem';
COMMENT ON COLUMN morse_claimable_account_history.supplier_stake_denom IS 'Staked tokens for supplier actor corresponding to this account address DEV_NOTE: Context for Morse: - Supplier = Servicer or Node (not a full node) in Morse - All Validators are Servicers; not all Servicers are Validators - Top 100 staked Servicers are validators (automatic) - Only accounts for servicer stake balance transition TODO_MAINNET(@Olshansk): Develop strategy for bootstrapping validators in Shannon with cosmos ecosystem';
COMMENT ON COLUMN morse_claimable_account_history.application_stake_amount IS 'Staked tokens for application actor corresponding to this account address';
COMMENT ON COLUMN morse_claimable_account_history.application_stake_denom IS 'Staked tokens for application actor corresponding to this account address';
COMMENT ON COLUMN morse_claimable_account_history.claimed_at_height IS 'Shannon height at which the account was claimed Intended to remain empty until the account is claimed';

-- cosmos.bank.v1beta1.Metadata → cosmos_bank_metadata_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN cosmos_bank_metadata_history.name IS 'name defines the name of the token (eg: Cosmos Atom)';
COMMENT ON COLUMN cosmos_bank_metadata_history.symbol IS 'symbol is the token symbol usually shown on exchanges (eg: ATOM). This can be the same as the display.';
COMMENT ON COLUMN cosmos_bank_metadata_history.uri IS 'URI to a document (on or off-chain) that contains additional information. Optional.';
COMMENT ON COLUMN cosmos_bank_metadata_history.uri_hash IS 'URIHash is a sha256 hash of a document pointed by URI. It''s used to verify that the document didn''t change. Optional.';

-- cosmos.staking.v1beta1.Validator → cosmos_staking_validator_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN cosmos_staking_validator_history.min_self_delegation IS 'min_self_delegation is the validator''s self declared minimum self delegation.';

-- cosmos.gov.v1.Proposal → cosmos_gov_proposal_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN cosmos_gov_proposal_history.title IS 'title is the title of the proposal';
COMMENT ON COLUMN cosmos_gov_proposal_history.summary IS 'summary is a short summary of the proposal';
COMMENT ON COLUMN cosmos_gov_proposal_history.proposer IS 'proposer is the address of the proposal sumbitter';
COMMENT ON COLUMN cosmos_gov_proposal_history.expedited IS 'expedited defines if the proposal is expedited';
COMMENT ON COLUMN cosmos_gov_proposal_history.failed_reason IS 'failed_reason defines the reason why the proposal failed';

-- cosmos.bank.v1beta1.GenesisState → cosmos_bank_genesis_state (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN cosmos_bank_genesis_state.send_enabled IS 'send_enabled defines the denoms where send is enabled or disabled.';

-- cosmos.gov.v1.GenesisState → cosmos_gov_genesis_state (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN cosmos_gov_genesis_state.params IS 'params defines all the paramaters of x/gov module.';
COMMENT ON COLUMN cosmos_gov_genesis_state.constitution IS 'The constitution allows builders to lay a foundation and define purpose. This is an immutable string set in genesis. There are no amendments, to go outside of scope, just fork. constitution is an immutable string in genesis for a chain builder to lay out their vision, ideas and ideals.';

-- cosmos.gov.v1.MsgSubmitProposal → cosmos_gov_v1_msg_submit_proposal (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN cosmos_gov_v1_msg_submit_proposal.title IS 'title is the title of the proposal.';
COMMENT ON COLUMN cosmos_gov_v1_msg_submit_proposal.summary IS 'summary is the summary of the proposal';
COMMENT ON COLUMN cosmos_gov_v1_msg_submit_proposal.expedited IS 'expedited defines if the proposal is expedited or not';

-- cosmos.gov.v1.Params → cosmos_gov_params_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN cosmos_gov_params_history.proposal_cancel_ratio IS 'The cancel ratio which will not be returned back to the depositors when a proposal is cancelled.';
COMMENT ON COLUMN cosmos_gov_params_history.proposal_cancel_dest IS 'The address which will receive (proposal_cancel_ratio * deposit) proposal deposits. If empty, the (proposal_cancel_ratio * deposit) proposal deposits will be burned.';
COMMENT ON COLUMN cosmos_gov_params_history.expedited_voting_period IS 'Duration of the voting period of an expedited proposal.';
COMMENT ON COLUMN cosmos_gov_params_history.expedited_threshold IS 'Minimum proportion of Yes votes for proposal to pass. Default value: 0.67.';
COMMENT ON COLUMN cosmos_gov_params_history.min_deposit_ratio IS 'The ratio representing the proportion of the deposit value minimum that must be met when making a deposit. Default value: 0.01. Meaning that for a chain with a min_deposit of 100stake, a deposit of 1stake would be required.';

-- cosmos.group.v1.MsgSubmitProposal → cosmos_group_v1_msg_submit_proposal (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN cosmos_group_v1_msg_submit_proposal.title IS 'title is the title of the proposal.';
COMMENT ON COLUMN cosmos_group_v1_msg_submit_proposal.summary IS 'summary is the summary of the proposal.';

-- pocket.migration.EventImportMorseClaimableAccounts → event_import_morse_claimable_accounts (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN event_import_morse_claimable_accounts.created_at_height IS 'Shannon height at which MorseAccountState was created on-chain';
COMMENT ON COLUMN event_import_morse_claimable_accounts.morse_account_state_hash IS 'On-chain computed sha256 hash of the MorseAccountState - Contains all imported MorseClaimableAccounts';
COMMENT ON COLUMN event_import_morse_claimable_accounts.num_accounts IS 'Number of claimable accounts (EOAs) imported from Morse state export - Account balances include consolidated application and supplier actor stakes';

-- pocket.migration.EventMorseAccountClaimed → event_morse_account_claimed (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN event_morse_account_claimed.session_end_height IS 'Shannon session end height in which the claim was committed';
COMMENT ON COLUMN event_morse_account_claimed.claimed_balance_amount IS 'Unstaked balance claimed from Morse';
COMMENT ON COLUMN event_morse_account_claimed.claimed_balance_denom IS 'Unstaked balance claimed from Morse';
COMMENT ON COLUMN event_morse_account_claimed.shannon_dest_address IS 'bech32-encoded Shannon address to mint claimed balance';
COMMENT ON COLUMN event_morse_account_claimed.morse_src_address IS 'Hex-encoded Morse account address whose balance was claimed';

-- pocket.migration.EventMorseApplicationClaimed → event_morse_application_claimed (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN event_morse_application_claimed.session_end_height IS 'Shannon session end height in which the claim was committed';
COMMENT ON COLUMN event_morse_application_claimed.claimed_balance_amount IS 'Unstaked balance claimed from Morse';
COMMENT ON COLUMN event_morse_application_claimed.claimed_balance_denom IS 'Unstaked balance claimed from Morse';
COMMENT ON COLUMN event_morse_application_claimed.morse_src_address IS 'Hex-encoded Morse account address whose balance was claimed';
COMMENT ON COLUMN event_morse_application_claimed.claimed_application_stake_amount IS 'Application stake claimed as a result of the claim - Equivalent to Morse application staked amount';
COMMENT ON COLUMN event_morse_application_claimed.claimed_application_stake_denom IS 'Application stake claimed as a result of the claim - Equivalent to Morse application staked amount';
COMMENT ON COLUMN event_morse_application_claimed.application IS 'Application staked as a result of the claim - Mirrors Morse application stake';

-- pocket.migration.EventMorseSupplierClaimed → event_morse_supplier_claimed (additive)
ALTER TABLE event_morse_supplier_claimed ADD COLUMN IF NOT EXISTS morse_node_address TEXT NULL;
ALTER TABLE event_morse_supplier_claimed ADD COLUMN IF NOT EXISTS morse_output_address TEXT NULL;
ALTER TABLE event_morse_supplier_claimed ADD COLUMN IF NOT EXISTS claim_signer_type JSONB NULL;
COMMENT ON COLUMN event_morse_supplier_claimed.morse_node_address IS 'The hex-encoded address of the Morse non-custodial (i.e. operator) account. - Unstaked balance was migrated 1:1 - Stake was migrated 1:1 from morse_node_address to shannon_operator_address - Morse non-custodial (i.e. operator) address. If morse_output_address was not set, this is the custodial address. - See ''pocket nodes --help'' for more information. Note that this refers to the Morse CLI. E.g.: 00f9900606fa3d5c9179fc0c8513078a53a2073e';
COMMENT ON COLUMN event_morse_supplier_claimed.morse_output_address IS 'ONLY applicable to Morse node/supplier accounts. Hex-encoded address of the Morse output account/wallet associated with the Morse node/supplier. - E.g.: 00f9900606fa3d5c9179fc0c8513078a53a2073e - Morse custodial (i.e. owner) address, which owned the staked tokens of the operator. See ''pocket nodes --help'' for more information. Note that this refers to the Morse CLI.';
COMMENT ON COLUMN event_morse_supplier_claimed.claim_signer_type IS 'The type of supplier claim signer, indicating which actor executed the claim and whether it was a custodial or non-custodial claim. - MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_NON_CUSTODIAL_SIGNED_BY_ADDR - MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_CUSTODIAL_SIGNED_BY_OPERATOR - MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_CUSTODIAL_SIGNED_BY_OWNER';
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN event_morse_supplier_claimed.session_end_height IS 'Shannon session end height in which the claim was committed';
COMMENT ON COLUMN event_morse_supplier_claimed.claimed_balance_amount IS 'Unstaked balance claimed from Morse';
COMMENT ON COLUMN event_morse_supplier_claimed.claimed_balance_denom IS 'Unstaked balance claimed from Morse';
COMMENT ON COLUMN event_morse_supplier_claimed.claimed_supplier_stake_amount IS 'Supplier stake claimed as a result of the claim - Equivalent to Morse supplier staked amount';
COMMENT ON COLUMN event_morse_supplier_claimed.claimed_supplier_stake_denom IS 'Supplier stake claimed as a result of the claim - Equivalent to Morse supplier staked amount';
COMMENT ON COLUMN event_morse_supplier_claimed.supplier IS 'Supplier staked as a result of the claim - Mirrors Morse supplier stake';
-- REMOVED in v0.1.12: column morse_src_address kept (append-only, ADR-005).

-- pocket.migration.MsgClaimMorseSupplier → msg_claim_morse_supplier (additive)
ALTER TABLE msg_claim_morse_supplier ADD COLUMN IF NOT EXISTS morse_node_address TEXT NULL;
ALTER TABLE msg_claim_morse_supplier ADD COLUMN IF NOT EXISTS signer_is_output_address BOOLEAN NULL;
COMMENT ON COLUMN msg_claim_morse_supplier.morse_node_address IS 'The hex-encoded address of the Morse non-custodial (i.e. operator) account. - Unstaked balance will be migrated 1:1 - Stake will be migrated 1:1 from morse_node_address to shannon_operator_address - Morse non-custodial (i.e. operator) address. If morse_output_address is not set, this is the custodial address. - See ''pocket nodes --help'' for more information. Note that this refers to the Morse CLI. E.g.: 00f9900606fa3d5c9179fc0c8513078a53a2073e';
COMMENT ON COLUMN msg_claim_morse_supplier.signer_is_output_address IS 'Set to true if the private key corresponding to the morse_output_address is producing the morse_signature. For non-custodial claiming: - This MUST be true. - The morse_public_key MUST correspond to morse_output_address. - The morse_signature MUST correspond to morse_output_address.';
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN msg_claim_morse_supplier.morse_public_key IS 'The ed25519 public key of EITHER the Morse node/supplier operator OR owner account. - MUST correspond to the private key which was used to produce the morse_signature. - MUST correspond to ONE OF THE FOLLOWING: - morse_node_address - morse_output_address';
COMMENT ON COLUMN msg_claim_morse_supplier.morse_signature IS 'The hex-encoded signature, of this message (where this field is nil). I.e.: morse_signature = private_key.sign(marshal(MsgClaimMorseSupplier{morse_signature: nil, ...})) - MUST match morse_public_key. - MUST be signed by ONE OF THE FOLLOWING: - Morse node account (i.e. operator); if signer_is_output_address is false - Morse output account (i.e. owner); if signer_is_output_address is true';

-- pocket.migration.MsgImportMorseClaimableAccounts → msg_import_morse_claimable_accounts (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN msg_import_morse_claimable_accounts.morse_account_state IS 'Account state derived from Morse state export and `pocketd tx migration collect-morse-accounts`';
COMMENT ON COLUMN msg_import_morse_claimable_accounts.morse_account_state_hash IS 'Validates the morse_account_state sha256 hash: - Transaction fails if hash doesn''t match on-chain computation - Off-chain social consensus should be reached before verification  Verification (high-level): $ pocketd tx migration collect-morse-accounts $<(pocket util export-genesis-for-reset)  Additional docs: - pocket util export-genesis-for-migration --help - pocketd tx migration collect-morse-accounts --help';

-- pocket.migration.MsgUpdateParams → msg_update_params (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN msg_update_params.params IS 'Module parameters to update NOTE: All parameters must be supplied';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE morse_validator_history DROP COLUMN IF EXISTS output_address;
ALTER TABLE morse_claimable_account_history DROP COLUMN IF EXISTS morse_output_address;
ALTER TABLE event_morse_supplier_claimed DROP COLUMN IF EXISTS morse_node_address;
ALTER TABLE event_morse_supplier_claimed DROP COLUMN IF EXISTS morse_output_address;
ALTER TABLE event_morse_supplier_claimed DROP COLUMN IF EXISTS claim_signer_type;
ALTER TABLE msg_claim_morse_supplier DROP COLUMN IF EXISTS morse_node_address;
ALTER TABLE msg_claim_morse_supplier DROP COLUMN IF EXISTS signer_is_output_address;
DROP TABLE IF EXISTS cosmos_benchmark_v1_msg_load_test CASCADE;
DROP TABLE IF EXISTS cosmos_counter_v1_msg_increase_counter CASCADE;
DROP TABLE IF EXISTS cosmos_epochs_vb1_event_epoch_end CASCADE;
DROP TABLE IF EXISTS cosmos_epochs_vb1_event_epoch_start CASCADE;
DROP TABLE IF EXISTS cosmos_epochs_genesis_state CASCADE;
DROP TABLE IF EXISTS cosmos_protocolpool_genesis_state CASCADE;
DROP TABLE IF EXISTS cosmos_protocolpool_v1_msg_cancel_continuous_fund CASCADE;
DROP TABLE IF EXISTS cosmos_protocolpool_v1_msg_community_pool_spend CASCADE;
DROP TABLE IF EXISTS cosmos_protocolpool_v1_msg_create_continuous_fund CASCADE;
DROP TABLE IF EXISTS cosmos_protocolpool_v1_msg_fund_community_pool CASCADE;
DROP TABLE IF EXISTS cosmos_protocolpool_v1_msg_update_params CASCADE;
DROP TABLE IF EXISTS cosmos_protocolpool_params_history CASCADE;
DROP TABLE IF EXISTS event_morse_account_recovered CASCADE;
DELETE FROM decoder_version WHERE tag = 'v0.1.12';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
