-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.13.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_13.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (113, 'v0.1.13')
ON CONFLICT (tag) DO NOTHING;

-- pocket.migration.MorseApplication → morse_application_history (additive)
ALTER TABLE morse_application_history ADD COLUMN IF NOT EXISTS unstaking_time JSONB NULL;
COMMENT ON COLUMN morse_application_history.unstaking_time IS 'The ISO 8601 UTC timestamp after which the Morse node/supplier unbonding period will have elapsed. It reflects the "unbonding completion time" of the Morse node/supplier, but is called "unstaking time" to comply with necessary Morse data structures.';

-- pocket.migration.MorseValidator → morse_validator_history (additive)
ALTER TABLE morse_validator_history ADD COLUMN IF NOT EXISTS unstaking_time JSONB NULL;
COMMENT ON COLUMN morse_validator_history.unstaking_time IS 'The ISO 8601 UTC timestamp after which the Morse node/supplier unbonding period will have elapsed. It reflects the "unbonding completion time" of the Morse node/supplier, but is called "unstaking time" to comply with necessary Morse data structures.';

-- pocket.migration.MorseClaimableAccount → morse_claimable_account_history (additive)
ALTER TABLE morse_claimable_account_history ADD COLUMN IF NOT EXISTS unstaking_time JSONB NULL;
COMMENT ON COLUMN morse_claimable_account_history.unstaking_time IS 'The ISO 8601 UTC timestamp after which the Morse node/supplier unbonding period will have elapsed. It reflects the "unbonding completion time" of the Morse node/supplier, but is called "unstaking time" to comply with necessary Morse data structures.';

-- pocket.migration.MsgClaimMorseAccount → msg_claim_morse_account (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN msg_claim_morse_account.shannon_signing_address IS 'The bech32-encoded address of the Shannon account which is signing for this message. This account is liable for any fees incurred by violating the constraints of Morse account/actor claim message fee waiving.';

-- pocket.migration.Params → migration_params_history (additive)
ALTER TABLE migration_params_history ADD COLUMN IF NOT EXISTS morse_account_claiming_enabled BOOLEAN NULL;
COMMENT ON COLUMN migration_params_history.morse_account_claiming_enabled IS 'morse_account_claiming_enabled is a feature flag which is used to enable/disable the processing of Morse account/actor claim messages (i.e. `MsgClaimMorseAccount`, `MorseClaimApplication`, and `MorseClaimSupplier`).';

-- pocket.shared.Params → shared_params_history (additive)
ALTER TABLE shared_params_history ADD COLUMN IF NOT EXISTS compute_unit_cost_granularity BIGINT NULL;
COMMENT ON COLUMN shared_params_history.compute_unit_cost_granularity IS 'compute_unit_cost_granularity is the fraction of the base unit (uPOKT) used to represent the smallest price of a single compute unit. compute_unit_cost_granularity defines the smallest fraction of uPOKT that can represent the cost of a single compute unit.  It acts as a denominator in the formula:  compute_unit_cost_in_uPOKT = compute_units_to_tokens_multiplier / compute_unit_cost_granularity  This enables high-precision pricing of compute units using integer math. For example:  +-------------------------------+---------------------------------------------+ | compute_unit_cost_granularity | compute_units_to_tokens_multiplier unit     | +-------------------------------+---------------------------------------------+ | 1                             | uPOKT                                       | | 1_000                         | nPOKT (nanoPOKT, 1e-3 uPOKT)                | | 1_000_000                     | pPOKT (picoPOKT, 1e-6 uPOKT)                | +-------------------------------+---------------------------------------------+  ⚠️ Note: This value is a configurable global network parameter (not a constant). It must be a power of 10, allowing precise denomination shifts without affecting ongoing sessions. This prevents sessions from settling using parameters that were not in effect during their creation.';
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN shared_params_history.compute_units_to_tokens_multiplier IS 'The amount of tokens that a compute unit should translate to when settling a session. It is denominated in fractional uPOKT (1/compute_unit_cost_granularity) DEV_NOTE: This used to be under x/tokenomics but has been moved here to avoid cyclic dependencies.';

-- pocket.tokenomics.EventClaimExpired → event_claim_expired (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN event_claim_expired.claimed_amount IS 'The uPOKT coin claimed to be rewarded for the work done as a function of the number of estimated compute units and the compute units to token multiplier.';
COMMENT ON COLUMN event_claim_expired.claimed_denom IS 'The uPOKT coin claimed to be rewarded for the work done as a function of the number of estimated compute units and the compute units to token multiplier.';

-- pocket.tokenomics.EventClaimSettled → event_claim_settled (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN event_claim_settled.claimed_amount IS 'The uPOKT coin claimed to be rewarded for the work done as a function of the number of estimated compute units and the compute units to token multiplier.';
COMMENT ON COLUMN event_claim_settled.claimed_denom IS 'The uPOKT coin claimed to be rewarded for the work done as a function of the number of estimated compute units and the compute units to token multiplier.';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE morse_application_history DROP COLUMN IF EXISTS unstaking_time;
ALTER TABLE morse_validator_history DROP COLUMN IF EXISTS unstaking_time;
ALTER TABLE morse_claimable_account_history DROP COLUMN IF EXISTS unstaking_time;
ALTER TABLE migration_params_history DROP COLUMN IF EXISTS morse_account_claiming_enabled;
ALTER TABLE shared_params_history DROP COLUMN IF EXISTS compute_unit_cost_granularity;
DELETE FROM decoder_version WHERE tag = 'v0.1.13';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
