-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.21.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_21.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (121, 'v0.1.21')
ON CONFLICT (tag) DO NOTHING;

-- pocket.session.Session → session_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN session_history.session_id IS 'A unique pseudorandom ID for this session';

-- pocket.proof.Claim → claim_history (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN claim_history.root_hash IS 'Root hash from smt.SMST#Root(). TODO_UP_NEXT(@bryanchriswhite, #1497): Dehydrate the claim''s root hash from onchain events.';

-- pocket.proof.EventProofSubmitted → event_proof_submitted (additive)
-- REMOVED in v0.1.21: column proof kept (append-only, ADR-005).

-- pocket.proof.EventProofUpdated → event_proof_updated (additive)
-- REMOVED in v0.1.21: column proof kept (append-only, ADR-005).

-- pocket.proof.EventProofValidityChecked → event_proof_validity_checked (additive)
ALTER TABLE event_proof_validity_checked ADD COLUMN IF NOT EXISTS claim JSONB NULL;
-- REMOVED in v0.1.21: column proof kept (append-only, ADR-005).
-- REMOVED in v0.1.21: column proof_status kept (append-only, ADR-005).

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE event_proof_validity_checked DROP COLUMN IF EXISTS claim;
DELETE FROM decoder_version WHERE tag = 'v0.1.21';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
