-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.23.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_23.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (123, 'v0.1.23')
ON CONFLICT (tag) DO NOTHING;

-- pocket.tokenomics.EventClaimDiscarded → event_claim_discarded (first appearance)
CREATE TABLE IF NOT EXISTS event_claim_discarded (
  claim JSONB NULL,
  error TEXT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT event_claim_discarded_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT event_claim_discarded_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('event_claim_discarded', 'block_time', if_not_exists => TRUE);
COMMENT ON COLUMN event_claim_discarded.error IS 'The error that caused the claim to be discarded.';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS event_claim_discarded CASCADE;
DELETE FROM decoder_version WHERE tag = 'v0.1.23';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
