-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.26.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_26.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (126, 'v0.1.26')
ON CONFLICT (tag) DO NOTHING;

-- pocket.tokenomics.EventClaimSettled → event_claim_settled (additive)
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS settlement_result JSONB NULL;
COMMENT ON COLUMN event_claim_settled.settlement_result IS 'SettlementResult holds mint, burn, and transfer operations on a per-claim basis.';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS settlement_result;
DELETE FROM decoder_version WHERE tag = 'v0.1.26';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
