-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.27.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_27.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (127, 'v0.1.27')
ON CONFLICT (tag) DO NOTHING;

-- pocket.migration.EventMorseAccountClaimed → event_morse_account_claimed (additive)
ALTER TABLE event_morse_account_claimed ADD COLUMN IF NOT EXISTS claimed_balance TEXT NULL;
COMMENT ON COLUMN event_morse_account_claimed.claimed_balance IS 'Unstaked balance claimed from Morse';
-- REMOVED in v0.1.27: column claimed_balance_amount kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column claimed_balance_denom kept (append-only, ADR-005).

-- pocket.migration.EventMorseAccountRecovered → event_morse_account_recovered (additive)
ALTER TABLE event_morse_account_recovered ADD COLUMN IF NOT EXISTS recovered_balance TEXT NULL;
COMMENT ON COLUMN event_morse_account_recovered.recovered_balance IS 'The total balance which was recovered: - Includes both unstaked and staked balances (consolidated) - Auto-liquidates both unstaked and staked balances at once';
-- REMOVED in v0.1.27: column recovered_balance_amount kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column recovered_balance_denom kept (append-only, ADR-005).

-- pocket.migration.EventMorseApplicationClaimed → event_morse_application_claimed (additive)
ALTER TABLE event_morse_application_claimed ADD COLUMN IF NOT EXISTS claimed_balance TEXT NULL;
ALTER TABLE event_morse_application_claimed ADD COLUMN IF NOT EXISTS claimed_application_stake TEXT NULL;
COMMENT ON COLUMN event_morse_application_claimed.claimed_balance IS 'Unstaked balance claimed from Morse';
COMMENT ON COLUMN event_morse_application_claimed.claimed_application_stake IS 'Application stake claimed as a result of the claim - Equivalent to Morse application staked amount';
-- REMOVED in v0.1.27: column claimed_balance_amount kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column claimed_balance_denom kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column claimed_application_stake_amount kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column claimed_application_stake_denom kept (append-only, ADR-005).

-- pocket.migration.EventMorseSupplierClaimed → event_morse_supplier_claimed (additive)
ALTER TABLE event_morse_supplier_claimed ADD COLUMN IF NOT EXISTS claimed_balance TEXT NULL;
ALTER TABLE event_morse_supplier_claimed ADD COLUMN IF NOT EXISTS claimed_supplier_stake TEXT NULL;
COMMENT ON COLUMN event_morse_supplier_claimed.claimed_balance IS 'Unstaked balance claimed from Morse';
COMMENT ON COLUMN event_morse_supplier_claimed.claimed_supplier_stake IS 'Supplier stake claimed as a result of the claim - Equivalent to Morse supplier staked amount';
-- REMOVED in v0.1.27: column claimed_balance_amount kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column claimed_balance_denom kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column claimed_supplier_stake_amount kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column claimed_supplier_stake_denom kept (append-only, ADR-005).

-- pocket.proof.EventClaimCreated → event_claim_created (additive)
ALTER TABLE event_claim_created ADD COLUMN IF NOT EXISTS service_id TEXT NULL;
ALTER TABLE event_claim_created ADD COLUMN IF NOT EXISTS application_address TEXT NULL;
ALTER TABLE event_claim_created ADD COLUMN IF NOT EXISTS session_end_block_height BIGINT NULL;
ALTER TABLE event_claim_created ADD COLUMN IF NOT EXISTS claim_proof_status_int INTEGER NULL;
ALTER TABLE event_claim_created ADD COLUMN IF NOT EXISTS supplier_operator_address TEXT NULL;
COMMENT ON COLUMN event_claim_created.service_id IS 'The Service ID to which the claim corresponds.';
COMMENT ON COLUMN event_claim_created.application_address IS 'The address of the application which participated in the claimed session.';
COMMENT ON COLUMN event_claim_created.session_end_block_height IS 'The end block height of the session to which the claim corresponds.';
COMMENT ON COLUMN event_claim_created.claim_proof_status_int IS 'The validation status of the claim. DEV_NOTE: This field uses the integer representation of the ClaimProofStatus enum to minimize onchain disk utilization. This is necessary because event data is not always protobuf-encoded in the various places and formats that it appears in onchain leveldb databases. Enum values: PENDING_VALIDATION = 0; VALIDATED = 1; INVALID = 2;';
COMMENT ON COLUMN event_claim_created.supplier_operator_address IS 'The operator address of the supplier which submitted the claim.';
-- REMOVED in v0.1.27: column claim kept (append-only, ADR-005).

-- pocket.proof.EventClaimUpdated → event_claim_updated (additive)
ALTER TABLE event_claim_updated ADD COLUMN IF NOT EXISTS service_id TEXT NULL;
ALTER TABLE event_claim_updated ADD COLUMN IF NOT EXISTS application_address TEXT NULL;
ALTER TABLE event_claim_updated ADD COLUMN IF NOT EXISTS session_end_block_height BIGINT NULL;
ALTER TABLE event_claim_updated ADD COLUMN IF NOT EXISTS claim_proof_status_int INTEGER NULL;
ALTER TABLE event_claim_updated ADD COLUMN IF NOT EXISTS supplier_operator_address TEXT NULL;
COMMENT ON COLUMN event_claim_updated.service_id IS 'The Service ID to which the claim corresponds.';
COMMENT ON COLUMN event_claim_updated.application_address IS 'The address of the application which participated in the claimed session.';
COMMENT ON COLUMN event_claim_updated.session_end_block_height IS 'The end block height of the session to which the claim corresponds.';
COMMENT ON COLUMN event_claim_updated.claim_proof_status_int IS 'The validation status of the claim. DEV_NOTE: This field uses the integer representation of the ClaimProofStatus enum to minimize onchain disk utilization. This is necessary because event data is not always protobuf-encoded in the various places and formats that it appears in onchain leveldb databases. Enum values: PENDING_VALIDATION = 0; VALIDATED = 1; INVALID = 2;';
COMMENT ON COLUMN event_claim_updated.supplier_operator_address IS 'The operator address of the supplier which updated the claim.';
-- REMOVED in v0.1.27: column claim kept (append-only, ADR-005).

-- pocket.proof.EventProofSubmitted → event_proof_submitted (additive)
ALTER TABLE event_proof_submitted ADD COLUMN IF NOT EXISTS service_id TEXT NULL;
ALTER TABLE event_proof_submitted ADD COLUMN IF NOT EXISTS application_address TEXT NULL;
ALTER TABLE event_proof_submitted ADD COLUMN IF NOT EXISTS session_end_block_height BIGINT NULL;
ALTER TABLE event_proof_submitted ADD COLUMN IF NOT EXISTS claim_proof_status_int INTEGER NULL;
ALTER TABLE event_proof_submitted ADD COLUMN IF NOT EXISTS supplier_operator_address TEXT NULL;
COMMENT ON COLUMN event_proof_submitted.service_id IS 'The Service ID to which the claim corresponds.';
COMMENT ON COLUMN event_proof_submitted.application_address IS 'The address of the application which participated in the claimed session.';
COMMENT ON COLUMN event_proof_submitted.session_end_block_height IS 'The end block height of the session to which the claim corresponds.';
COMMENT ON COLUMN event_proof_submitted.claim_proof_status_int IS 'The validation status of the claim. DEV_NOTE: This field uses the integer representation of the ClaimProofStatus enum to minimize onchain disk utilization. This is necessary because event data is not always protobuf-encoded in the various places and formats that it appears in onchain leveldb databases. Enum values: PENDING_VALIDATION = 0; VALIDATED = 1; INVALID = 2;';
COMMENT ON COLUMN event_proof_submitted.supplier_operator_address IS 'The operator address of the supplier which submitted the proof.';
-- REMOVED in v0.1.27: column claim kept (append-only, ADR-005).

-- pocket.proof.EventProofUpdated → event_proof_updated (additive)
ALTER TABLE event_proof_updated ADD COLUMN IF NOT EXISTS service_id TEXT NULL;
ALTER TABLE event_proof_updated ADD COLUMN IF NOT EXISTS application_address TEXT NULL;
ALTER TABLE event_proof_updated ADD COLUMN IF NOT EXISTS session_end_block_height BIGINT NULL;
ALTER TABLE event_proof_updated ADD COLUMN IF NOT EXISTS claim_proof_status_int INTEGER NULL;
ALTER TABLE event_proof_updated ADD COLUMN IF NOT EXISTS supplier_operator_address TEXT NULL;
COMMENT ON COLUMN event_proof_updated.service_id IS 'The Service ID to which the claim corresponds.';
COMMENT ON COLUMN event_proof_updated.application_address IS 'The address of the application which participated in the claimed session.';
COMMENT ON COLUMN event_proof_updated.session_end_block_height IS 'The end block height of the session to which the claim corresponds.';
COMMENT ON COLUMN event_proof_updated.claim_proof_status_int IS 'The validation status of the claim. DEV_NOTE: This field uses the integer representation of the ClaimProofStatus enum to minimize onchain disk utilization. This is necessary because event data is not always protobuf-encoded in the various places and formats that it appears in onchain leveldb databases. Enum values: PENDING_VALIDATION = 0; VALIDATED = 1; INVALID = 2;';
COMMENT ON COLUMN event_proof_updated.supplier_operator_address IS 'The operator address of the supplier which updated the proof.';
-- REMOVED in v0.1.27: column claim kept (append-only, ADR-005).

-- pocket.proof.EventProofValidityChecked → event_proof_validity_checked (additive)
ALTER TABLE event_proof_validity_checked ADD COLUMN IF NOT EXISTS service_id TEXT NULL;
ALTER TABLE event_proof_validity_checked ADD COLUMN IF NOT EXISTS application_address TEXT NULL;
ALTER TABLE event_proof_validity_checked ADD COLUMN IF NOT EXISTS session_end_block_height BIGINT NULL;
ALTER TABLE event_proof_validity_checked ADD COLUMN IF NOT EXISTS claim_proof_status_int INTEGER NULL;
ALTER TABLE event_proof_validity_checked ADD COLUMN IF NOT EXISTS supplier_operator_address TEXT NULL;
COMMENT ON COLUMN event_proof_validity_checked.service_id IS 'The Service ID to which the claim corresponds.';
COMMENT ON COLUMN event_proof_validity_checked.application_address IS 'The address of the application which participated in the claimed session.';
COMMENT ON COLUMN event_proof_validity_checked.session_end_block_height IS 'The end block height of the session to which the claim corresponds.';
COMMENT ON COLUMN event_proof_validity_checked.claim_proof_status_int IS 'The validation status of the claim. DEV_NOTE: This field uses the integer representation of the ClaimProofStatus enum to minimize onchain disk utilization. This is necessary because event data is not always protobuf-encoded in the various places and formats that it appears in onchain leveldb databases. Enum values: PENDING_VALIDATION = 0; VALIDATED = 1; INVALID = 2;';
COMMENT ON COLUMN event_proof_validity_checked.supplier_operator_address IS 'The operator address of the supplier whose proof was checked.';
-- REMOVED in v0.1.27: column claim kept (append-only, ADR-005).

-- pocket.supplier.EventSupplierServiceConfigActivated → event_supplier_service_config_activated (additive)
ALTER TABLE event_supplier_service_config_activated ADD COLUMN IF NOT EXISTS operator_address TEXT NULL;
ALTER TABLE event_supplier_service_config_activated ADD COLUMN IF NOT EXISTS service_id TEXT NULL;
COMMENT ON COLUMN event_supplier_service_config_activated.service_id IS 'The Service ID for which the supplier is configured';
-- REMOVED in v0.1.27: column supplier kept (append-only, ADR-005).

-- pocket.supplier.EventSupplierStaked → event_supplier_staked (additive)
ALTER TABLE event_supplier_staked ADD COLUMN IF NOT EXISTS operator_address TEXT NULL;
-- REMOVED in v0.1.27: column supplier kept (append-only, ADR-005).

-- pocket.tokenomics.EventApplicationOverserviced → event_application_overserviced (additive)
ALTER TABLE event_application_overserviced ADD COLUMN IF NOT EXISTS expected_burn TEXT NULL;
ALTER TABLE event_application_overserviced ADD COLUMN IF NOT EXISTS effective_burn TEXT NULL;
COMMENT ON COLUMN event_application_overserviced.expected_burn IS 'Expected number of tokens to be burnt from the application''s stake. A function of the actual amount of work claimed to be done.';
COMMENT ON COLUMN event_application_overserviced.effective_burn IS 'Actual number of tokens burnt from the application''s stake. A function of the amount that could be covered (less than) relative to the amount of work claimed to be done.';
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN event_application_overserviced.application_addr IS 'The application address consuming onchain services';
COMMENT ON COLUMN event_application_overserviced.supplier_operator_addr IS 'The supplier operator address providing onchain services';
-- REMOVED in v0.1.27: column expected_burn_amount kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column expected_burn_denom kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column effective_burn_amount kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column effective_burn_denom kept (append-only, ADR-005).

-- pocket.tokenomics.EventApplicationReimbursementRequest → event_application_reimbursement_request (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN event_application_reimbursement_request.application_addr IS 'The application address consuming onchain services requesting reimbursement.';
COMMENT ON COLUMN event_application_reimbursement_request.supplier_operator_addr IS 'The supplier operator address providing onchain services';
COMMENT ON COLUMN event_application_reimbursement_request.supplier_owner_addr IS 'The supplier owner address providing onchain services';
COMMENT ON COLUMN event_application_reimbursement_request.service_id IS 'The service ID associated with the session where a claim was submitted.';
COMMENT ON COLUMN event_application_reimbursement_request.session_id IS 'The session ID associated with the session where a claim was submitted.';
-- REMOVED in v0.1.27: column amount_denom kept (append-only, ADR-005).
-- TYPE CHANGE FLAG: amount BIGINT → TEXT. Verify decoder handles this; no destructive ALTER emitted.

-- pocket.tokenomics.EventClaimDiscarded → event_claim_discarded (additive)
ALTER TABLE event_claim_discarded ADD COLUMN IF NOT EXISTS service_id TEXT NULL;
ALTER TABLE event_claim_discarded ADD COLUMN IF NOT EXISTS application_address TEXT NULL;
ALTER TABLE event_claim_discarded ADD COLUMN IF NOT EXISTS session_end_block_height BIGINT NULL;
ALTER TABLE event_claim_discarded ADD COLUMN IF NOT EXISTS claim_proof_status_int INTEGER NULL;
ALTER TABLE event_claim_discarded ADD COLUMN IF NOT EXISTS supplier_operator_address TEXT NULL;
COMMENT ON COLUMN event_claim_discarded.service_id IS 'The Service ID to which the claim corresponds.';
COMMENT ON COLUMN event_claim_discarded.application_address IS 'The address of the application which participated in the claimed session.';
COMMENT ON COLUMN event_claim_discarded.session_end_block_height IS 'The end block height of the session to which the claim corresponds.';
COMMENT ON COLUMN event_claim_discarded.claim_proof_status_int IS 'The validation status of the claim. DEV_NOTE: This field uses the integer representation of the ClaimProofStatus enum to minimize onchain disk utilization. This is necessary because event data is not always protobuf-encoded in the various places and formats that it appears in onchain leveldb databases. Enum values: PENDING_VALIDATION = 0; VALIDATED = 1; INVALID = 2;';
COMMENT ON COLUMN event_claim_discarded.supplier_operator_address IS 'The operator address of the supplier whose claim was discarded.';
-- REMOVED in v0.1.27: column claim kept (append-only, ADR-005).

-- pocket.tokenomics.EventClaimExpired → event_claim_expired (additive)
ALTER TABLE event_claim_expired ADD COLUMN IF NOT EXISTS service_id TEXT NULL;
ALTER TABLE event_claim_expired ADD COLUMN IF NOT EXISTS application_address TEXT NULL;
ALTER TABLE event_claim_expired ADD COLUMN IF NOT EXISTS session_end_block_height BIGINT NULL;
ALTER TABLE event_claim_expired ADD COLUMN IF NOT EXISTS claim_proof_status_int INTEGER NULL;
ALTER TABLE event_claim_expired ADD COLUMN IF NOT EXISTS supplier_operator_address TEXT NULL;
COMMENT ON COLUMN event_claim_expired.service_id IS 'The Service ID to which the claim corresponds.';
COMMENT ON COLUMN event_claim_expired.application_address IS 'The address of the application which participated in the claimed session.';
COMMENT ON COLUMN event_claim_expired.session_end_block_height IS 'The end block height of the session to which the claim corresponds.';
COMMENT ON COLUMN event_claim_expired.claim_proof_status_int IS 'The validation status of the claim. DEV_NOTE: This field uses the integer representation of the ClaimProofStatus enum to minimize onchain disk utilization. This is necessary because event data is not always protobuf-encoded in the various places and formats that it appears in onchain leveldb databases. Enum values: PENDING_VALIDATION = 0; VALIDATED = 1; INVALID = 2;';
COMMENT ON COLUMN event_claim_expired.supplier_operator_address IS 'The operator address of the supplier whose claim expired.';
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN event_claim_expired.num_claimed_compute_units IS 'Number of compute units claimed in the session tree. It is a function of the number of relays in the session tree and onchain parameters.';
COMMENT ON COLUMN event_claim_expired.num_estimated_compute_units IS 'Number of total estimated compute units of work done. It is a function of the number of claimed compute units and the relay difficulty multiplier.';
COMMENT ON COLUMN event_claim_expired.claimed_amount IS 'The amount of uPOKT claimed for the work done. It is a function of the number of estimated compute units and the compute units to token multiplier.';
COMMENT ON COLUMN event_claim_expired.claimed_denom IS 'The amount of uPOKT claimed for the work done. It is a function of the number of estimated compute units and the compute units to token multiplier.';
-- REMOVED in v0.1.27: column claim kept (append-only, ADR-005).

-- pocket.tokenomics.EventClaimSettled → event_claim_settled (additive)
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS proof_requirement_int INTEGER NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS service_id TEXT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS application_address TEXT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS session_end_block_height BIGINT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS claim_proof_status_int INTEGER NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS supplier_operator_address TEXT NULL;
COMMENT ON COLUMN event_claim_settled.proof_requirement_int IS 'Whether a proof was required for the claim to be settled. DEV_NOTE: This field uses the integer representation of the ProofRequirementReason enum to minimize onchain disk utilization. This is necessary because event data is not always protobuf-encoded in the various places and formats that it appears in onchain leveldb databases. Enum values: NOT_REQUIRED = 0; PROBABILISTIC = 1; THRESHOLD = 2;';
COMMENT ON COLUMN event_claim_settled.service_id IS 'The Service ID to which the claim corresponds.';
COMMENT ON COLUMN event_claim_settled.application_address IS 'The address of the application which participated in the claimed session.';
COMMENT ON COLUMN event_claim_settled.session_end_block_height IS 'The end block height of the session to which the claim corresponds.';
COMMENT ON COLUMN event_claim_settled.claim_proof_status_int IS 'The validation status of the claim. DEV_NOTE: This field uses the integer representation of the ClaimProofStatus enum to minimize onchain disk utilization. This is necessary because event data is not always protobuf-encoded in the various places and formats that it appears in onchain leveldb databases. Enum values: PENDING_VALIDATION = 0; VALIDATED = 1; INVALID = 2;';
COMMENT ON COLUMN event_claim_settled.supplier_operator_address IS 'The operator address of the supplier who submitted the claim.';
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN event_claim_settled.num_claimed_compute_units IS 'Number of compute units claimed in the session tree. It is a function of the number of relays in the session tree and onchain parameters.';
COMMENT ON COLUMN event_claim_settled.num_estimated_compute_units IS 'Number of estimated compute units claimed in the session tree. It is a function of the number of claimed compute units and the relay difficulty multiplier for the particular service.';
-- REMOVED in v0.1.27: column claim kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column proof_requirement kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column settlement_result kept (append-only, ADR-005).

-- pocket.tokenomics.EventSupplierSlashed → event_supplier_slashed (additive)
ALTER TABLE event_supplier_slashed ADD COLUMN IF NOT EXISTS proof_missing_penalty TEXT NULL;
ALTER TABLE event_supplier_slashed ADD COLUMN IF NOT EXISTS service_id TEXT NULL;
ALTER TABLE event_supplier_slashed ADD COLUMN IF NOT EXISTS application_address TEXT NULL;
ALTER TABLE event_supplier_slashed ADD COLUMN IF NOT EXISTS session_end_block_height BIGINT NULL;
ALTER TABLE event_supplier_slashed ADD COLUMN IF NOT EXISTS claim_proof_status_int INTEGER NULL;
ALTER TABLE event_supplier_slashed ADD COLUMN IF NOT EXISTS supplier_operator_address TEXT NULL;
COMMENT ON COLUMN event_supplier_slashed.proof_missing_penalty IS 'Amount slashed from the supplier''s stake. A function of the claim size, supplier stake, and various onchain parameters.';
COMMENT ON COLUMN event_supplier_slashed.service_id IS 'The Service ID to which the claim corresponds.';
COMMENT ON COLUMN event_supplier_slashed.application_address IS 'The address of the application which participated in the claimed session.';
COMMENT ON COLUMN event_supplier_slashed.session_end_block_height IS 'The end block height of the session to which the claim corresponds.';
COMMENT ON COLUMN event_supplier_slashed.claim_proof_status_int IS 'The validation status of the claim. DEV_NOTE: This field uses the integer representation of the ClaimProofStatus enum to minimize onchain disk utilization. This is necessary because event data is not always protobuf-encoded in the various places and formats that it appears in onchain leveldb databases. Enum values: PENDING_VALIDATION = 0; VALIDATED = 1; INVALID = 2;';
COMMENT ON COLUMN event_supplier_slashed.supplier_operator_address IS 'The operator address of the supplier that was slashed.';
-- REMOVED in v0.1.27: column claim kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column proof_missing_penalty_amount kept (append-only, ADR-005).
-- REMOVED in v0.1.27: column proof_missing_penalty_denom kept (append-only, ADR-005).

-- pocket.tokenomics.MsgUpdateParam → msg_update_param (additive)
ALTER TABLE msg_update_param ADD COLUMN IF NOT EXISTS as_mint_equals_burn_claim_distribution JSONB NULL;

-- pocket.tokenomics.MsgUpdateParams → msg_update_params (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN msg_update_params.params IS 'params defines the tokenomics parameters to update.';

-- pocket.tokenomics.Params → tokenomics_params_history (additive)
ALTER TABLE tokenomics_params_history ADD COLUMN IF NOT EXISTS mint_equals_burn_claim_distribution JSONB NULL;
COMMENT ON COLUMN tokenomics_params_history.mint_equals_burn_claim_distribution IS 'mint_equals_burn_claim_distribution controls how the settlement amount is distributed when global inflation is disabled (global_inflation_per_claim = 0). MintEqualsBurnTLM: Only used by the MintEqualsBurnTLM at the end of claim settlement.';
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN tokenomics_params_history.dao_reward_address IS 'dao_reward_address is where the DAO''s portion of claims submitted are distributed.';
COMMENT ON COLUMN tokenomics_params_history.mint_allocation_percentages IS 'mint_allocation_percentages represents the distribution of newly minted tokens. GlobalMintTLM: Only used by the GlobalMintTLM at the end of claim settlement.';
COMMENT ON COLUMN tokenomics_params_history.global_inflation_per_claim IS 'global_inflation_per_claim is the percentage of a claim''s claimable uPOKT amount to be minted on settlement. GlobalMintTLM: Only used by the GlobalMintTLM at the end of claim settlement.';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE event_morse_account_claimed DROP COLUMN IF EXISTS claimed_balance;
ALTER TABLE event_morse_account_recovered DROP COLUMN IF EXISTS recovered_balance;
ALTER TABLE event_morse_application_claimed DROP COLUMN IF EXISTS claimed_balance;
ALTER TABLE event_morse_application_claimed DROP COLUMN IF EXISTS claimed_application_stake;
ALTER TABLE event_morse_supplier_claimed DROP COLUMN IF EXISTS claimed_balance;
ALTER TABLE event_morse_supplier_claimed DROP COLUMN IF EXISTS claimed_supplier_stake;
ALTER TABLE event_claim_created DROP COLUMN IF EXISTS service_id;
ALTER TABLE event_claim_created DROP COLUMN IF EXISTS application_address;
ALTER TABLE event_claim_created DROP COLUMN IF EXISTS session_end_block_height;
ALTER TABLE event_claim_created DROP COLUMN IF EXISTS claim_proof_status_int;
ALTER TABLE event_claim_created DROP COLUMN IF EXISTS supplier_operator_address;
ALTER TABLE event_claim_updated DROP COLUMN IF EXISTS service_id;
ALTER TABLE event_claim_updated DROP COLUMN IF EXISTS application_address;
ALTER TABLE event_claim_updated DROP COLUMN IF EXISTS session_end_block_height;
ALTER TABLE event_claim_updated DROP COLUMN IF EXISTS claim_proof_status_int;
ALTER TABLE event_claim_updated DROP COLUMN IF EXISTS supplier_operator_address;
ALTER TABLE event_proof_submitted DROP COLUMN IF EXISTS service_id;
ALTER TABLE event_proof_submitted DROP COLUMN IF EXISTS application_address;
ALTER TABLE event_proof_submitted DROP COLUMN IF EXISTS session_end_block_height;
ALTER TABLE event_proof_submitted DROP COLUMN IF EXISTS claim_proof_status_int;
ALTER TABLE event_proof_submitted DROP COLUMN IF EXISTS supplier_operator_address;
ALTER TABLE event_proof_updated DROP COLUMN IF EXISTS service_id;
ALTER TABLE event_proof_updated DROP COLUMN IF EXISTS application_address;
ALTER TABLE event_proof_updated DROP COLUMN IF EXISTS session_end_block_height;
ALTER TABLE event_proof_updated DROP COLUMN IF EXISTS claim_proof_status_int;
ALTER TABLE event_proof_updated DROP COLUMN IF EXISTS supplier_operator_address;
ALTER TABLE event_proof_validity_checked DROP COLUMN IF EXISTS service_id;
ALTER TABLE event_proof_validity_checked DROP COLUMN IF EXISTS application_address;
ALTER TABLE event_proof_validity_checked DROP COLUMN IF EXISTS session_end_block_height;
ALTER TABLE event_proof_validity_checked DROP COLUMN IF EXISTS claim_proof_status_int;
ALTER TABLE event_proof_validity_checked DROP COLUMN IF EXISTS supplier_operator_address;
ALTER TABLE event_supplier_service_config_activated DROP COLUMN IF EXISTS operator_address;
ALTER TABLE event_supplier_service_config_activated DROP COLUMN IF EXISTS service_id;
ALTER TABLE event_supplier_staked DROP COLUMN IF EXISTS operator_address;
ALTER TABLE event_application_overserviced DROP COLUMN IF EXISTS expected_burn;
ALTER TABLE event_application_overserviced DROP COLUMN IF EXISTS effective_burn;
ALTER TABLE event_claim_discarded DROP COLUMN IF EXISTS service_id;
ALTER TABLE event_claim_discarded DROP COLUMN IF EXISTS application_address;
ALTER TABLE event_claim_discarded DROP COLUMN IF EXISTS session_end_block_height;
ALTER TABLE event_claim_discarded DROP COLUMN IF EXISTS claim_proof_status_int;
ALTER TABLE event_claim_discarded DROP COLUMN IF EXISTS supplier_operator_address;
ALTER TABLE event_claim_expired DROP COLUMN IF EXISTS service_id;
ALTER TABLE event_claim_expired DROP COLUMN IF EXISTS application_address;
ALTER TABLE event_claim_expired DROP COLUMN IF EXISTS session_end_block_height;
ALTER TABLE event_claim_expired DROP COLUMN IF EXISTS claim_proof_status_int;
ALTER TABLE event_claim_expired DROP COLUMN IF EXISTS supplier_operator_address;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS proof_requirement_int;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS service_id;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS application_address;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS session_end_block_height;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS claim_proof_status_int;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS supplier_operator_address;
ALTER TABLE event_supplier_slashed DROP COLUMN IF EXISTS proof_missing_penalty;
ALTER TABLE event_supplier_slashed DROP COLUMN IF EXISTS service_id;
ALTER TABLE event_supplier_slashed DROP COLUMN IF EXISTS application_address;
ALTER TABLE event_supplier_slashed DROP COLUMN IF EXISTS session_end_block_height;
ALTER TABLE event_supplier_slashed DROP COLUMN IF EXISTS claim_proof_status_int;
ALTER TABLE event_supplier_slashed DROP COLUMN IF EXISTS supplier_operator_address;
ALTER TABLE msg_update_param DROP COLUMN IF EXISTS as_mint_equals_burn_claim_distribution;
ALTER TABLE tokenomics_params_history DROP COLUMN IF EXISTS mint_equals_burn_claim_distribution;
DELETE FROM decoder_version WHERE tag = 'v0.1.27';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
