-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.30.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_30.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (130, 'v0.1.30')
ON CONFLICT (tag) DO NOTHING;

-- pocket.shared.Service → service_history (additive)
ALTER TABLE service_history ADD COLUMN IF NOT EXISTS metadata JSONB NULL;
COMMENT ON COLUMN service_history.metadata IS 'Optional metadata containing an experimental API specification for the service. When exposed via JSON, this field is base64 encoded and MUST be <= 256 KiB when decoded.';

-- pocket.service.MsgAddService → msg_add_service (additive)
-- COMMENT refreshes (proto docstring changed since previous version)
COMMENT ON COLUMN msg_add_service.service IS 'The Service being added to the network, including optional experimental metadata';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE service_history DROP COLUMN IF EXISTS metadata;
DELETE FROM decoder_version WHERE tag = 'v0.1.30';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
