-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.31.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_31.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (131, 'v0.1.31')
ON CONFLICT (tag) DO NOTHING;

-- pocket.migration.EventMorseAccountRecoveredAdmin → event_morse_account_recovered_admin (first appearance)
CREATE TABLE IF NOT EXISTS event_morse_account_recovered_admin (
  session_end_height BIGINT NULL,
  recovered_balance TEXT NULL,
  shannon_dest_address TEXT NULL,
  morse_src_address TEXT NULL,
  is_admin_recovery BOOLEAN NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT event_morse_account_recovered_admin_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT event_morse_account_recovered_admin_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('event_morse_account_recovered_admin', 'block_time', if_not_exists => TRUE);
COMMENT ON COLUMN event_morse_account_recovered_admin.session_end_height IS 'The session end height (on Shannon) in which the recovery was committed.';
COMMENT ON COLUMN event_morse_account_recovered_admin.recovered_balance IS 'The total balance which was recovered (both unstaked and staked balances).';
COMMENT ON COLUMN event_morse_account_recovered_admin.shannon_dest_address IS 'The bech32-encoded address of the Shannon account to which the recovered balance was minted.';
COMMENT ON COLUMN event_morse_account_recovered_admin.morse_src_address IS 'The hex-encoded address of the Morse account whose balance and stakes have been recovered. NOTE: This address was NOT checked against the allowlist - admin recovery bypasses allowlist validation.';
COMMENT ON COLUMN event_morse_account_recovered_admin.is_admin_recovery IS 'Flag to indicate this was an admin recovery (always true for this event type). Useful for filtering/monitoring admin recoveries vs regular recoveries.';

-- pocket.migration.MsgAdminRecoverMorseAccount → msg_admin_recover_morse_account (first appearance)
CREATE TABLE IF NOT EXISTS msg_admin_recover_morse_account (
  authority TEXT NULL,
  shannon_dest_address TEXT NULL,
  morse_src_address TEXT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT msg_admin_recover_morse_account_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT msg_admin_recover_morse_account_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('msg_admin_recover_morse_account', 'block_time', if_not_exists => TRUE);
COMMENT ON COLUMN msg_admin_recover_morse_account.authority IS 'The bech32-encoded address of the migration module authority account. ONLY the authority MAY call this admin recovery function.';
COMMENT ON COLUMN msg_admin_recover_morse_account.shannon_dest_address IS 'The bech32-encoded address of the Shannon account to receive recovered tokens.';
COMMENT ON COLUMN msg_admin_recover_morse_account.morse_src_address IS 'The hex-encoded address of the Morse account to recover. NOTE: This address is NOT checked against the allowlist. The authority is trusted to validate recovery requests off-chain.';

-- pocket.tokenomics.Params → tokenomics_params_history (additive)
ALTER TABLE tokenomics_params_history ADD COLUMN IF NOT EXISTS mint_ratio DOUBLE PRECISION NULL;
COMMENT ON COLUMN tokenomics_params_history.mint_ratio IS 'mint_ratio is the proportion of burned tokens to mint (0.0 < mint_ratio <= 1.0). PIP-41: A value of 0.975 means 97.5% of burned tokens are minted, 2.5% permanently removed. MintEqualsBurnTLM: Only used by the MintEqualsBurnTLM at the end of claim settlement. Default: 1.0 (no deflation - mint equals burn for backward compatibility)';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE tokenomics_params_history DROP COLUMN IF EXISTS mint_ratio;
DROP TABLE IF EXISTS event_morse_account_recovered_admin CASCADE;
DROP TABLE IF EXISTS msg_admin_recover_morse_account CASCADE;
DELETE FROM decoder_version WHERE tag = 'v0.1.31';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
