-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.33.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_33.json
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (133, 'v0.1.33')
ON CONFLICT (tag) DO NOTHING;

-- pocket.service.MsgTransferService → msg_transfer_service (first appearance)
CREATE TABLE IF NOT EXISTS msg_transfer_service (
  owner_address TEXT NULL,
  service_id TEXT NULL,
  new_owner_address TEXT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT msg_transfer_service_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT msg_transfer_service_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('msg_transfer_service', 'block_time', if_not_exists => TRUE);
COMMENT ON COLUMN msg_transfer_service.owner_address IS 'The Bech32 address of the current service owner (signer).';
COMMENT ON COLUMN msg_transfer_service.service_id IS 'The unique identifier of the service to transfer.';
COMMENT ON COLUMN msg_transfer_service.new_owner_address IS 'The Bech32 address of the new service owner.';

-- pocket.tokenomics.EventSettlementBatch → event_settlement_batch (first appearance)
CREATE TABLE IF NOT EXISTS event_settlement_batch (
  session_end_block_height BIGINT NULL,
  sender_module TEXT NULL,
  recipient TEXT NULL,
  op_reason JSONB NULL,
  total_amount TEXT NULL,
  num_claims INTEGER NULL,
  op_type TEXT NULL,
  block_height BIGINT NOT NULL,
  block_time TIMESTAMPTZ NOT NULL,
  tx_index INTEGER NOT NULL DEFAULT 0,
  event_index INTEGER NOT NULL DEFAULT 0,
  decoded_by_version SMALLINT NOT NULL,
  indexed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT event_settlement_batch_pk PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT event_settlement_batch_decoder_fk FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('event_settlement_batch', 'block_time', if_not_exists => TRUE);
COMMENT ON COLUMN event_settlement_batch.session_end_block_height IS 'The session end block height for the batch of settlements.';
COMMENT ON COLUMN event_settlement_batch.sender_module IS 'The sender module account (or destination module for mints/burns).';
COMMENT ON COLUMN event_settlement_batch.recipient IS 'The recipient (bech32 address for mod-to-acct, module name for mod-to-mod, empty for mints/burns).';
COMMENT ON COLUMN event_settlement_batch.op_reason IS 'The settlement operation reason from the TLM.';
COMMENT ON COLUMN event_settlement_batch.total_amount IS 'The total aggregated amount as a coin string.';
COMMENT ON COLUMN event_settlement_batch.num_claims IS 'Number of individual claims that contributed to this batch.';
COMMENT ON COLUMN event_settlement_batch.op_type IS 'The type of bank operation: "mint", "burn", "mod_to_mod", "mod_to_acct".';

-- pocket.application.Application → application_history (additive)
ALTER TABLE application_history ADD COLUMN IF NOT EXISTS per_session_spend_limit_amount BIGINT NULL;
ALTER TABLE application_history ADD COLUMN IF NOT EXISTS per_session_spend_limit_denom TEXT NULL;
COMMENT ON COLUMN application_history.per_session_spend_limit_amount IS 'Optional per-session spend limit in uPOKT. When set, caps the maximum amount of stake consumed per session. Nil = no limit (default).';
COMMENT ON COLUMN application_history.per_session_spend_limit_denom IS 'Optional per-session spend limit in uPOKT. When set, caps the maximum amount of stake consumed per session. Nil = no limit (default).';

-- pocket.application.MsgStakeApplication → msg_stake_application (additive)
ALTER TABLE msg_stake_application ADD COLUMN IF NOT EXISTS per_session_spend_limit_amount BIGINT NULL;
ALTER TABLE msg_stake_application ADD COLUMN IF NOT EXISTS per_session_spend_limit_denom TEXT NULL;
COMMENT ON COLUMN msg_stake_application.per_session_spend_limit_amount IS 'Optional per-session spend limit in uPOKT. Three-way semantics: nil/omitted = preserve existing limit, zero = clear limit, positive = set new limit.';
COMMENT ON COLUMN msg_stake_application.per_session_spend_limit_denom IS 'Optional per-session spend limit in uPOKT. Three-way semantics: nil/omitted = preserve existing limit, zero = clear limit, positive = set new limit.';

-- pocket.session.GenesisState → session_genesis_state (additive)
ALTER TABLE session_genesis_state ADD COLUMN IF NOT EXISTS params_history JSONB NULL;
COMMENT ON COLUMN session_genesis_state.params_history IS 'params_history contains historical params snapshots for height-based lookups.';

-- pocket.shared.GenesisState → shared_genesis_state (additive)
ALTER TABLE shared_genesis_state ADD COLUMN IF NOT EXISTS params_history JSONB NULL;
COMMENT ON COLUMN shared_genesis_state.params_history IS 'params_history contains historical params snapshots for height-based lookups.';

-- pocket.tokenomics.EventApplicationOverserviced → event_application_overserviced (additive)
ALTER TABLE event_application_overserviced ADD COLUMN IF NOT EXISTS service_id TEXT NULL;
ALTER TABLE event_application_overserviced ADD COLUMN IF NOT EXISTS session_end_block_height BIGINT NULL;
ALTER TABLE event_application_overserviced ADD COLUMN IF NOT EXISTS spend_limit_exceeded BOOLEAN NULL;
COMMENT ON COLUMN event_application_overserviced.service_id IS 'The Service ID for the session where overservicing occurred. Enables unambiguous joins with EventClaimSettled.';
COMMENT ON COLUMN event_application_overserviced.session_end_block_height IS 'The session end block height where overservicing occurred. Together with service_id, application_addr, and supplier_operator_addr, this uniquely identifies the corresponding EventClaimSettled.';
COMMENT ON COLUMN event_application_overserviced.spend_limit_exceeded IS 'Whether overservicing was triggered by per_session_spend_limit (true) vs the standard stake-based cap (false, default).';

-- pocket.tokenomics.EventClaimSettled → event_claim_settled (additive)
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS reward_distribution_detailed JSONB NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS settled_amount BIGINT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS settled_denom TEXT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS mint_ratio TEXT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS session_id TEXT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS supplier_owner_address TEXT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS num_estimated_relays BIGINT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS minted_amount BIGINT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS minted_denom TEXT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS overservicing_loss_amount BIGINT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS overservicing_loss_denom TEXT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS deflation_loss_amount BIGINT NULL;
ALTER TABLE event_claim_settled ADD COLUMN IF NOT EXISTS deflation_loss_denom TEXT NULL;
COMMENT ON COLUMN event_claim_settled.reward_distribution_detailed IS 'Detailed per-reason reward breakdown. Unlike reward_distribution (field 14) which merges all reasons per address, this preserves the OpReason for each entry.';
COMMENT ON COLUMN event_claim_settled.settled_amount IS 'The actual settlement amount after overservicing cap, before mint_ratio. Indexers can compute: overservicing_loss = claimed_upokt - settled_upokt';
COMMENT ON COLUMN event_claim_settled.settled_denom IS 'The actual settlement amount after overservicing cap, before mint_ratio. Indexers can compute: overservicing_loss = claimed_upokt - settled_upokt';
COMMENT ON COLUMN event_claim_settled.mint_ratio IS 'The mint_ratio applied during settlement (from tokenomics params). Indexers can compute: deflation_loss = settled_upokt * (1 - mint_ratio)';
COMMENT ON COLUMN event_claim_settled.session_id IS 'The unique session ID hash for this claim''s session. Enables direct joins without needing composite keys (app + service + session_end).';
COMMENT ON COLUMN event_claim_settled.supplier_owner_address IS 'The owner address of the supplier who submitted the claim. Useful when owner != operator (delegated staking) for attributing rewards.';
COMMENT ON COLUMN event_claim_settled.num_estimated_relays IS 'The probabilistic estimation of the total number of relays served in this session. Derived from the relay mining difficulty: num_estimated_relays = num_relays * difficulty_multiplier. Unlike num_relays (which is only the count of leaves in the session tree that matched the relay mining difficulty), this reflects the actual estimated workload.';
COMMENT ON COLUMN event_claim_settled.minted_amount IS 'The actual amount of uPOKT minted for this claim via the Relay Burn Equals Mint TLM. minted_upokt = settled_upokt * mint_ratio (truncated to integer). This is the real economic value created by this claim after both overservicing and deflation. Relationship: claimed_upokt >= settled_upokt >= minted_upokt';
COMMENT ON COLUMN event_claim_settled.minted_denom IS 'The actual amount of uPOKT minted for this claim via the Relay Burn Equals Mint TLM. minted_upokt = settled_upokt * mint_ratio (truncated to integer). This is the real economic value created by this claim after both overservicing and deflation. Relationship: claimed_upokt >= settled_upokt >= minted_upokt';
COMMENT ON COLUMN event_claim_settled.overservicing_loss_amount IS 'The amount of uPOKT lost to overservicing for this claim. overservicing_loss_upokt = claimed_upokt - settled_upokt. Zero when the supplier''s claim fits within the application''s per-supplier budget.';
COMMENT ON COLUMN event_claim_settled.overservicing_loss_denom IS 'The amount of uPOKT lost to overservicing for this claim. overservicing_loss_upokt = claimed_upokt - settled_upokt. Zero when the supplier''s claim fits within the application''s per-supplier budget.';
COMMENT ON COLUMN event_claim_settled.deflation_loss_amount IS 'The amount of uPOKT permanently removed from circulation (deflation) for this claim. deflation_loss_upokt = settled_upokt - minted_upokt = settled_upokt * (1 - mint_ratio). Zero when mint_ratio = 1 (no deflation).';
COMMENT ON COLUMN event_claim_settled.deflation_loss_denom IS 'The amount of uPOKT permanently removed from circulation (deflation) for this claim. deflation_loss_upokt = settled_upokt - minted_upokt = settled_upokt * (1 - mint_ratio). Zero when mint_ratio = 1 (no deflation).';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE application_history DROP COLUMN IF EXISTS per_session_spend_limit_amount;
ALTER TABLE application_history DROP COLUMN IF EXISTS per_session_spend_limit_denom;
ALTER TABLE msg_stake_application DROP COLUMN IF EXISTS per_session_spend_limit_amount;
ALTER TABLE msg_stake_application DROP COLUMN IF EXISTS per_session_spend_limit_denom;
ALTER TABLE session_genesis_state DROP COLUMN IF EXISTS params_history;
ALTER TABLE shared_genesis_state DROP COLUMN IF EXISTS params_history;
ALTER TABLE event_application_overserviced DROP COLUMN IF EXISTS service_id;
ALTER TABLE event_application_overserviced DROP COLUMN IF EXISTS session_end_block_height;
ALTER TABLE event_application_overserviced DROP COLUMN IF EXISTS spend_limit_exceeded;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS reward_distribution_detailed;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS settled_amount;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS settled_denom;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS mint_ratio;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS session_id;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS supplier_owner_address;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS num_estimated_relays;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS minted_amount;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS minted_denom;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS overservicing_loss_amount;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS overservicing_loss_denom;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS deflation_loss_amount;
ALTER TABLE event_claim_settled DROP COLUMN IF EXISTS deflation_loss_denom;
DROP TABLE IF EXISTS msg_transfer_service CASCADE;
DROP TABLE IF EXISTS event_settlement_batch CASCADE;
DELETE FROM decoder_version WHERE tag = 'v0.1.33';
-- decoder_version table NOT dropped (other migrations depend on it).
-- +goose StatementEnd
