-- +goose Up
-- +goose StatementBegin

-- ─────────────────────────────────────────────────────────────────────────
-- Auto-generated by /generate-migration-from-diff for poktroll v0.1.34.
-- Idempotent. See .claude/skills/generate-migration-from-diff/SKILL.md.
-- Source snapshot: docs/research/.shapes/v0_1_34.json
-- Shape break: pocket.tokenomics.EventSupplierSlashed gains tag=9
--   supplier_stake_after_slash (string). Seven new messages added.
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS decoder_version (
    id        SMALLINT PRIMARY KEY,
    tag       TEXT UNIQUE NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE decoder_version IS
    'Lookup of decoder packages. Populated by /generate-migration-from-diff. '
    'Referenced by every entity row via decoded_by_version.';

INSERT INTO decoder_version (id, tag) VALUES (134, 'v0.1.34')
ON CONFLICT (tag) DO NOTHING;

-- pocket.tokenomics.EventSupplierSlashed → event_supplier_slashed (additive)
-- v0.1.34 adds supplier_stake_after_slash (tag=9): supplier remaining stake
-- after the slash, capped at 0. Pre-v0.1.34 rows default to NULL.
ALTER TABLE event_supplier_slashed ADD COLUMN IF NOT EXISTS supplier_stake_after_slash TEXT NULL;
COMMENT ON COLUMN event_supplier_slashed.supplier_stake_after_slash IS
    'v0.1.34+: supplier remaining stake after slash, as uPOKT coin string '
    '(e.g. "99000000upokt"). NULL for rows decoded by earlier versions.';

-- pocket.application.EventApplicationStakeStuckInModulePool (first appearance)
CREATE TABLE IF NOT EXISTS event_application_stake_stuck_in_module_pool (
  application_address TEXT NULL,
  stuck_amount        BIGINT NULL,
  stuck_denom         TEXT NULL,
  reason              TEXT NULL,
  session_end_height  BIGINT NULL,
  block_height        BIGINT NOT NULL,
  block_time          TIMESTAMPTZ NOT NULL,
  tx_index            INTEGER NOT NULL DEFAULT 0,
  event_index         INTEGER NOT NULL DEFAULT 0,
  decoded_by_version  SMALLINT NOT NULL,
  indexed_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT event_application_stake_stuck_in_module_pool_pk
    PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT event_application_stake_stuck_in_module_pool_decoder_fk
    FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('event_application_stake_stuck_in_module_pool', 'block_time', if_not_exists => TRUE);
COMMENT ON TABLE event_application_stake_stuck_in_module_pool IS
    'Emitted when an application''s stake return fails and funds are stuck in '
    'the application module pool. Indicates a bank-module send rejection.';
COMMENT ON COLUMN event_application_stake_stuck_in_module_pool.application_address IS
    'Address of the application whose stake is stuck.';
COMMENT ON COLUMN event_application_stake_stuck_in_module_pool.stuck_amount IS
    'Amount of stuck coin in the application module pool (base units).';
COMMENT ON COLUMN event_application_stake_stuck_in_module_pool.stuck_denom IS
    'Denom of stuck coin in the application module pool.';
COMMENT ON COLUMN event_application_stake_stuck_in_module_pool.reason IS
    'Bank-module error string captured at the time of the failed send. Free-form.';
COMMENT ON COLUMN event_application_stake_stuck_in_module_pool.session_end_height IS
    'Session-end height of the EndBlocker that attempted the return-of-stake.';

-- pocket.supplier.EventSupplierStakeStuckInModulePool (first appearance)
CREATE TABLE IF NOT EXISTS event_supplier_stake_stuck_in_module_pool (
  operator_address    TEXT NULL,
  owner_address       TEXT NULL,
  stuck_amount        BIGINT NULL,
  stuck_denom         TEXT NULL,
  reason              TEXT NULL,
  session_end_height  BIGINT NULL,
  block_height        BIGINT NOT NULL,
  block_time          TIMESTAMPTZ NOT NULL,
  tx_index            INTEGER NOT NULL DEFAULT 0,
  event_index         INTEGER NOT NULL DEFAULT 0,
  decoded_by_version  SMALLINT NOT NULL,
  indexed_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT event_supplier_stake_stuck_in_module_pool_pk
    PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT event_supplier_stake_stuck_in_module_pool_decoder_fk
    FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('event_supplier_stake_stuck_in_module_pool', 'block_time', if_not_exists => TRUE);
COMMENT ON TABLE event_supplier_stake_stuck_in_module_pool IS
    'Emitted when a supplier''s stake return fails and funds are stuck in '
    'the supplier module pool. Indicates a bank-module send rejection.';
COMMENT ON COLUMN event_supplier_stake_stuck_in_module_pool.operator_address IS
    'Operator address of the supplier whose stake is stuck.';
COMMENT ON COLUMN event_supplier_stake_stuck_in_module_pool.owner_address IS
    'Owner address the bank module refused to send to.';
COMMENT ON COLUMN event_supplier_stake_stuck_in_module_pool.stuck_amount IS
    'Amount of stuck coin in the supplier module pool (base units).';
COMMENT ON COLUMN event_supplier_stake_stuck_in_module_pool.stuck_denom IS
    'Denom of stuck coin in the supplier module pool.';
COMMENT ON COLUMN event_supplier_stake_stuck_in_module_pool.reason IS
    'Bank-module error string captured at the time of the failed send. Free-form.';
COMMENT ON COLUMN event_supplier_stake_stuck_in_module_pool.session_end_height IS
    'Session-end height of the EndBlocker that attempted the return-of-stake.';

-- pocket.tokenomics.EventSupplierRevShareFallbackDistribution (first appearance)
CREATE TABLE IF NOT EXISTS event_supplier_rev_share_fallback_distribution (
  supplier_operator_address TEXT NULL,
  supplier_owner_address    TEXT NULL,
  service_id                TEXT NULL,
  session_end_block_height  BIGINT NULL,
  amount                    TEXT NULL,
  op_reason                 SMALLINT NULL,
  observed_sum_percentage   BIGINT NULL,
  reason                    TEXT NULL,
  block_height              BIGINT NOT NULL,
  block_time                TIMESTAMPTZ NOT NULL,
  tx_index                  INTEGER NOT NULL DEFAULT 0,
  event_index               INTEGER NOT NULL DEFAULT 0,
  decoded_by_version        SMALLINT NOT NULL,
  indexed_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT event_supplier_rev_share_fallback_distribution_pk
    PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT event_supplier_rev_share_fallback_distribution_decoder_fk
    FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('event_supplier_rev_share_fallback_distribution', 'block_time', if_not_exists => TRUE);
COMMENT ON TABLE event_supplier_rev_share_fallback_distribution IS
    'Emitted when a supplier''s revshare config is rejected and the full '
    'supplier slice is paid to the owner_address as fallback.';
COMMENT ON COLUMN event_supplier_rev_share_fallback_distribution.supplier_operator_address IS
    'Operator address of the supplier whose revshare config was rejected.';
COMMENT ON COLUMN event_supplier_rev_share_fallback_distribution.supplier_owner_address IS
    'Owner address that received the full supplier slice as fallback.';
COMMENT ON COLUMN event_supplier_rev_share_fallback_distribution.service_id IS
    'Service ID for the claim whose distribution triggered the fallback.';
COMMENT ON COLUMN event_supplier_rev_share_fallback_distribution.session_end_block_height IS
    'Session end block height of the settled claim that triggered the fallback.';
COMMENT ON COLUMN event_supplier_rev_share_fallback_distribution.amount IS
    'Full amount paid to the owner as fallback, as a coin string (e.g. "1000upokt").';
COMMENT ON COLUMN event_supplier_rev_share_fallback_distribution.op_reason IS
    'Settlement operation reason (TLM source) that produced the supplier slice. Integer of SettlementOpReason enum.';
COMMENT ON COLUMN event_supplier_rev_share_fallback_distribution.observed_sum_percentage IS
    'Observed sum of revshare percentages (should be 100; deviation triggers this event).';
COMMENT ON COLUMN event_supplier_rev_share_fallback_distribution.reason IS
    'Human-readable reason for the fallback (e.g. "sum 110 != 100").';

-- pocket.tokenomics.EventValidatorRewardDistribution (first appearance)
CREATE TABLE IF NOT EXISTS event_validator_reward_distribution (
  session_end_block_height      BIGINT NULL,
  op_reason                     SMALLINT NULL,
  validator_operator_address    TEXT NULL,
  validator_account_address     TEXT NULL,
  commission_rate               TEXT NULL,
  pool_share_upokt              TEXT NULL,
  commission_upokt              TEXT NULL,
  self_delegation_reward_upokt  TEXT NULL,
  delegators_reward_upokt       TEXT NULL,
  total_delegated_stake_upokt   TEXT NULL,
  num_delegators                INTEGER NULL,
  block_height                  BIGINT NOT NULL,
  block_time                    TIMESTAMPTZ NOT NULL,
  tx_index                      INTEGER NOT NULL DEFAULT 0,
  event_index                   INTEGER NOT NULL DEFAULT 0,
  decoded_by_version            SMALLINT NOT NULL,
  indexed_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT event_validator_reward_distribution_pk
    PRIMARY KEY (block_time, block_height, tx_index, event_index),
  CONSTRAINT event_validator_reward_distribution_decoder_fk
    FOREIGN KEY (decoded_by_version) REFERENCES decoder_version(id)
);
SELECT create_hypertable('event_validator_reward_distribution', 'block_time', if_not_exists => TRUE);
COMMENT ON TABLE event_validator_reward_distribution IS
    'Per-validator, per-op_reason reward summary emitted once per bonded '
    'validator per settlement block. Preserves the full commission/delegation '
    'breakdown without per-delegator events.';
COMMENT ON COLUMN event_validator_reward_distribution.session_end_block_height IS
    'Session end block height for the batch of settlements (first session on multi-session paths).';
COMMENT ON COLUMN event_validator_reward_distribution.op_reason IS
    'Settlement operation reason distinguishing Mint=Burn from Global Mint pools. Integer of SettlementOpReason enum.';
COMMENT ON COLUMN event_validator_reward_distribution.validator_operator_address IS
    'Validator operator (valoper...) address.';
COMMENT ON COLUMN event_validator_reward_distribution.validator_account_address IS
    'Validator account (pokt...) address; commission and self-delegation slice paid here.';
COMMENT ON COLUMN event_validator_reward_distribution.commission_rate IS
    'Validator commission rate as a decimal string (e.g. "0.100000000000000000").';
COMMENT ON COLUMN event_validator_reward_distribution.pool_share_upokt IS
    'Validator slice of the total proposer reward pool, in upokt.';
COMMENT ON COLUMN event_validator_reward_distribution.commission_upokt IS
    'Commission carved out of pool_share_upokt and paid to the validator account, in upokt.';
COMMENT ON COLUMN event_validator_reward_distribution.self_delegation_reward_upokt IS
    'Validator own self-delegation slice of the post-commission remainder, in upokt.';
COMMENT ON COLUMN event_validator_reward_distribution.delegators_reward_upokt IS
    'Portion of post-commission remainder paid to external delegators, in upokt.';
COMMENT ON COLUMN event_validator_reward_distribution.total_delegated_stake_upokt IS
    'Total delegated stake backing this validator (incl. self-delegation), in upokt.';
COMMENT ON COLUMN event_validator_reward_distribution.num_delegators IS
    'Number of external (non-self) delegators that received a reward from this validator.';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE event_supplier_slashed DROP COLUMN IF EXISTS supplier_stake_after_slash;
DROP TABLE IF EXISTS event_application_stake_stuck_in_module_pool CASCADE;
DROP TABLE IF EXISTS event_supplier_stake_stuck_in_module_pool CASCADE;
DROP TABLE IF EXISTS event_supplier_rev_share_fallback_distribution CASCADE;
DROP TABLE IF EXISTS event_validator_reward_distribution CASCADE;
DELETE FROM decoder_version WHERE tag = 'v0.1.34';
-- decoder_version table NOT dropped (other migrations depend on it).

-- +goose StatementEnd
